### ISSUE TITLE
ResetIf HitCount

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#1]
_From @Jamiras on March 21, 2018 14:26_

As a developer, I'd like to create a ResetIf condition that only resets the achievement if it happens a certain number of times.

We already have several examples of "Defeat boss without taking damage", but it's impossible to do something like "Defeat boss without jumping more than three times". To do that, you'd need a counter on the ResetIf condition.

Just like regular conditions, when the ResetIf condition is true, it will increment the counter. When the counter reaches the target, then the achievement will be reset.

Because it's tied to a HitCount, any other ResetIf in the achievement may reset its HitCount, but that's desirable as the entire achievement is supposed to reset if any ResetIf is true.

Existing achievements should be audited. Anything with a ResetIf HitCount(1) will be compatible with the change as the counter will increment to 1 and immediate reset the achievement. Anything with a ResetIf HitCount(>1) will have to be modified. As the HitCount clause currently has no effect on the ResetIf conditions, they should be changed to HitCount(0).

_Copied from original issue: RetroAchievements/RASuite#54_

**Comment by Jamiras** [comment]
I've audited all existing achievements and modified the following that had a ResetIf hit count > 1:
```
04728 Combatribes, The: 10350, 10351, 10352
09848 Action Man: Robot Atak: 58429
10554 Castle Of Illusion: Starring Mickey Mouse: 60260, 60262
10777 Wonder Boy in Monster Land: 58712
11750 Metal Slug: Super Vehicle-001: 59247
11805 Street Fighter Alpha: Warriors'' Dreams / Street Fighter Zero: 58756, 58757, 58758
```
