### ISSUE TITLE
Active Hits in Cheevo Descriptions

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAIntegration#102]
It would be useful to have a active Hits counter being displayed in the Cheevo Descriptions.
The implementation would work by using ID Requirements in the Description, for example:

- Displayed in RetroArch:
**Collect 10 (5) Apples.**
Nothing changed beside the **(5)** shows the current number of Hits/collected Apples.

- Code could look like following:
**Collect 10 [H=2] Apples.**
**[H=]** being the function to read Hits, **2** the ID in the Toolkit (Cheevo Requirement).

Having such function build into the Cheevo Descriptions would allow anyone to quickly open the Cheevo Menu and see all active Hits by browsing through the list of Cheevos, which Cheevo is alive (not reseted yet) or which Item has been collected/which one is missing, for example:

Cheevo List:

1. Deathless
**Finish Stage 1 without falling into a hole (1).**

1. Dragon Parts
**Collect Dragon Sword (1), Dragon Shield (1) and Dragon Armor (0).**

The Hits in Description could also be displayed on the Game Page / Cheevo Page, updated with the Rich Presence or just being hidden. Having such information on Web would also allow us to use the RP Space on the frontpage for other ingame informations.

**Comment by Jamiras** [comment]
I'm going to close this as a duplicate, but it's really an alternate solution for three separate ideas.

The Apples example would be handled by #4. A progress bar would be shown in the achievement list and popup messages could appear at milestones (design still in progress).

The Deathless example would be better handled by #52.

The Dragon Parts example doesn't really fit into either or those. It could be done using #33, but that might be overkill. If it's easy enough to see in game, adding the explicit checklist for the achievement seems unnecessary. If it's not easy to see in game, maybe the achievement should be re-evaluated.

Additionally, as suggested, this would affect RetroArch and the game page. Embedding the tag in the description _requires_ those to be updated to handle or ignore it. The other proposals all obscure the functionality in the conditions so only runtime support is required. We could add the progress bar to the standalone emus and RetroArch could add it's own bar (or even just a textual fraction) later.

I don't think it would be feasible to use the Rich Presence API call to update the meta descriptions for each user on their game page. It would only make sense to display per-user progress on the game pages if we store progress on the server to support multi-session achievements.
