### ISSUE TITLE
UINT_MAX and Rich Presence

### ISSUE THREAD

**Issue by BoomEX-UK** [RetroAchievements/RAIntegration#1042]
Hello,

Just hitting an issue that I thought could be with the code but appears to be more to do with the type that `FormatType=VALUE` is using.

When loading in very large numbers, rich presence seems to not cope with the value

![image](https://github.com/RetroAchievements/RAIntegration/assets/16966330/642c00d6-92e7-4220-8365-5f0b716bf79f)
is showing value `0xf8f5c6db` (dec 4176856795)

but rich presence is saying
![image](https://github.com/RetroAchievements/RAIntegration/assets/16966330/9126131e-16d1-42a9-80d8-e7209f9151c3)
```
Format:Credits
FormatType=VALUE

Display:
Main menu | 💰: @Credits(0xX1017400)
```

**Comment by Jamiras** [comment]
Working as designed. VALUE formatting reads the data as a signed integer. 

![image](https://github.com/RetroAchievements/RAIntegration/assets/32680403/bcd81130-2b10-475c-8baf-a88ab43721c5)

**Comment by BoomEX-UK** [comment]
Thank you for the fast response [Jamiras](https://github.com/Jamiras).

Is there a way to show 32-Bit unsigned on RP?

**Comment by Jamiras** [comment]
Unsigned value format was added in the 1.3.0 release of the DLL via #1056.
