### ISSUE TITLE
Offline Mode for developing and earning cheevos

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAIntegration#112]
A Offline Mode would be nice for those of us who have a unstable internet connection or just want to work/play offline and then sync their progress manually to the server, similar to PSN/XBL.

### Developing Offline
Making the entire developing progress offline compatible and allow to save a set/cheevos in one package-file, which can easily be transfered from one device to another device.

### Earning Offline
A switch in the Emulators (like Hardcore) which turns on the 'Offline Mode'. Offline Mode would function similar to Softcore but it will require to Sync the earnings to users profile, all progress will be saved locally as well. Also being able to load the one package-file which contains every data for developing and earning cheevos incl. cheevo badges anytime a user want, with saving progress of which cheevo has been earned.

This way users can share their custom sets in form of a single file with other users without uploading their content to the Site.

**Comment by Jamiras** [comment]
Developing offline is already covered by #21, but it specifically states that earning achievements offline should be a separate issue, so please update this to reflect that.

The package-file concept is a new idea. The plan was just to leverage the existing files in RACache. Will have to think about that more.
