### ISSUE TITLE
Minor bug report: Inaccurate conflict warning

### ISSUE THREAD

**Issue by suspect15** [RetroAchievements/RAIntegration#1120]
I'm receiving what I think is an inaccurate conflict warning.  Here is a screenshot of the achievement at trigger:
![image](https://github.com/user-attachments/assets/c8a611ca-e637-4141-bae1-7481e15c7f85)

This is an achievement for Chaos Legion (PS2)

Conditions 1 is a difficulty check

Conditions 2, 3 and 4 look for 0x005c1444's value to change from greater than 0 to 0 while 0x005c1478 remains greater than 0.  This uniquely happens at the end of a stage and serves as effective save/quit out protection.

Conditions 5 and 6 check that a player's Total Exp earned is at least greater than 2x the collected Exp (0x0051c444) which ensures they received a AAA+ rating.

The achievement functions correctly.

**Comment by Jamiras** [comment]
It's just reporting that 2 and 6 are conflicting. "A>0" cannot be true if "0>A" is also true.

It's supposed to be ignoring chains containing AddSource. I'll investigate.
