### ISSUE TITLE
Passwords are not URL-escaped

### ISSUE THREAD

**Issue by ubergeek77** [RetroAchievements/RAIntegration#114]
I wasn't able to log in to RA through any of the emulator apps, so I changed my password to a simple one. I was able to log in with this simple password. After changing my password back to a more complex one, I wasn't able to log in again. This made me think it was an issue with not escaping special characters on the login request. I skimmed the source code, and saw that passwords are sent as-is without any checks to see if the characters are valid URL characters. Sure enough, after manually escaping my password and pasting the escaped version into RAIntegration's password field, I was able to log in.

For clarification, please consider the following example:

Let's say this string is my password (it's not my real password!): s3?AJhs:u+S=D<%-]@{O

If I use this string as-is in RAIntegration, my login will fail, even though I would be able to log in to RetroAchievements.org with this very password.

However, if I enter an _**escaped**_ version into RAIntegration, my login will succeed without issue. So my above password would become:

s3%3FAJhs%3Au%2BS%3DD%3C%25-%5D%40%7BO

So instead of sending this request:

`https://retroachievements.org/login_app.php?u=ubergeek77&p=s3?AJhs:u+S=D<%-]@{O`

it sends this request:

`https://retroachievements.org/login_app.php?u=ubergeek77&p=s3%3FAJhs%3Au%2BS%3DD%3C%25-%5D%40%7BO`

and the server can properly read the password and send the appropriate response.

RAIntegration should really be doing this manually, as sending _**any**_ URL request before properly sanitizing it is bad practice.

**Comment by luchaos** [comment]
on that note: no passwords nor tokens should be sent as query string parameters ideally. we should/will address this with the new api.

**Comment by Jamiras** [comment]
A better solution for this would be to send the password in the POST data. It should not be in the query string, but we can address that at a later time.

> sending any URL request before properly sanitizing it is bad practice.

Yes, and it's causing issues in places other than just here. I'm planning to replace the existing HTTP layer with a interface/service in the next month or so, and was hoping to implement a blanket solution.

**Comment by Jamiras** [comment]
Brief testing suggests the password is already being sent in the POST data, but we're sending `Content-Type: application/x-www-form-urlencoded`, so it does still need to be escaped.
