### ISSUE TITLE
fix the logic to check new emus version

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#123]
Looking at the [`RA_CheckForUpdate()` in `RA_Core.cpp`](https://github.com/RetroAchievements/RAIntegration/blob/73cfb9689cc2c402294776bb48eb61421ffe294d/src/RA_Core.cpp#L902), it seems that the logic only recognize versions starting with `0.`.

This method is unable to handle RALibretro's versions (currently 1.0.12).

Related to RetroAchievements/RALibretro#25.

**Comment by Jamiras** [comment]
That code is associated with the "Check for Updates" menu option, and is broken for other reasons (it's expecting a string and getting a JSON response). However, there's [similar code](https://github.com/RetroAchievements/RAIntegration/blob/73cfb9689cc2c402294776bb48eb61421ffe294d/src/RA_Core.cpp#L714) in the callback from `RA_InitI` that has the same problem.

As a side note, I [fixed that logic for the DLL](https://github.com/RetroAchievements/RAIntegration/commit/35ec2483ea5626e5c991f2d6d791d9cb054e70b3#diff-2e4f23af2d3e03161f75690ac3dd875d) in the last set of emu releases.

**Comment by Jamiras** [comment]
Note that the server is not currently returning a version for RALibRetro:
```
{"Success":false,"Error":"Unknown client! (ConsoleID: 25)"}
```
25 is Atari 2600: https://github.com/RetroAchievements/RAIntegration/blob/master/src/RA_Core.cpp#L166

**Comment by meleu** [comment]
> Note that the server is not currently returning a version for RALibRetro

Yeah, I was about to solve it this morning, it seems to be simple to solve. But unfortunately faced some RL issues.
I hope to be back in a couple of days. :+1:
