### ISSUE TITLE
Rich presence edit/reload shortcuts

### ISSUE THREAD

**Issue by CoolCanuck** [RetroAchievements/RAIntegration#133]
As a developer creating rich presence, I would like a way to easily edit and reload from the rich presence monitor window. Ideas:
1. Open the responsible text file (eg: when double clicking title bar) using the default text editor, instead of looking for the game id on RA and finding the correct RAcache location.
2. Reload the local rich presence file (eg: double clicking the window area [not title bar]). This behaviour can already be done by using the RetroAchievements menu item to click on Rich Presence Monitor again, so not a big deal. A hotkey would be nice.

**Comment by kdecks** [comment]
My opinions is this isn't worth the effort.

**Comment by Jamiras** [comment]
I've opted for a solution that simply monitors the file for changes while the Rich Presence Monitor window is open.
