### ISSUE TITLE
make leaderboard cancel on reset

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#14]
_From @meleu on April 1, 2018 13:46_

Currently Leaderboards don't cancel on Reset.

A cheater can, for example, start a "hi-score on hard difficulty" leaderboard, reset the game, change the difficulty to easy and play.

I consider this a bug.

_Copied from original issue: RetroAchievements/RASuite#71_

**Comment by Jamiras** [comment]
Relevant changes have been merged for the RAEmus. Code on both sides of the integration is complete, we just need both sides to be distributed. Closing this.
