### ISSUE TITLE
show ConsoleName in "Unknown Title" dialog box

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#140]
As a RALibretro (multi-emulator) user I would like to know in what console library I'm about to add a game title when this dialog appears:
![image](https://camo.githubusercontent.com/be4a9d2919e4ac631ad78c6bb125eed24218c3c0/68747470733a2f2f692e696d6775722e636f6d2f7a4a4f6d6c58432e706e67)

Suggestion: put in the window title something like this: `Unknown Title for ConsoleName`.

**Comment by salvadorc17** [comment]
This is not Integration issue, or just Ralibretro dont send console name to integration, when creating a rom link with RA_Onloadnewrom function

**Comment by meleu** [comment]
:gitgud:

**Comment by Jamiras** [comment]
>This is not Integration issue, or just Ralibretro dont send console name to integration, when creating a rom link with RA_Onloadnewrom function

I'm not sure what you mean by this. `RA_OnLoadNewRom` only takes the ROM pointer and size. `RA_SetConsoleID` is used to indicate which console is running, but that doesn't currently have any effect on this particular dialog. Nor does anything in the dialog look at the current console (or current client). 

I do believe this is an integration issue.

**Comment by SyrianBallaS** [comment]
I can volunteer to do this. I tried it just for RANes and it shows "NES" instead of "Unknown Title". It's pretty simple I'll just do the same thing for all the ConsoleIDs.

**Comment by Jamiras** [comment]
When that gets converted to a viewmodel, the title will be the emulator name. I was planning to change "Unrecognized Title" to "Unrecognized Title: NES" or something along those lines. 

If you're ready to start working on features, I should probably formalize and share my roadmap. I'll try to get something put together this weekend.

If you want something to start looking at now, you could try to convert the RequestGamesList and SubmitNewTitle APIs, which are used by this dialog.

**Comment by SyrianBallaS** [comment]
There's a few rule sets I want to apply before working on large scale things so the analysis can be more of a maintenance thing. Having a roadmap would help though.
