### ISSUE TITLE
feature request: Ability to Sort and Edit Bookmarks

### ISSUE THREAD

**Issue by Blazekickn** [RetroAchievements/RAIntegration#145]
Title is self-explanatory.

**Comment by Keltron3030** [comment]
Would also like a native drop-down of noted addresses for adding to bookmarks rather than having to switch to and select from the memory inspector drop down and then click add.

**Comment by kdecks** [comment]
It is possible to edit bookmarks by double clicking the description.

**Comment by Blazekickn** [comment]
You can edit the description but you can't change the address it tracks or whether it's 8/16/32-bit

**Comment by Jamiras** [comment]
The new bookmark dialog allows for sorting and editing of name/size/format. It does not allow changing the address.
