### ISSUE TITLE
Naming and Layout/Style Proposal

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#15]
_From @SyrianBallaS on April 3, 2018 19:25_

<h1>Preface</h1>
<p>
  OK, so I noticed the .editorconfig file got accepted. That will definitely help a little bit, but ultimately not 
  solve the root issue of inconsistent style. It is understandable that inconsistencies are undesirable and wish 
  to propose a solution. Some of these come from the reviews in pull request #49, others from myself, and, isocpp.
  For some insight, I professionaly program in ASP.NET Core so some stylings may differ from isocpp.
</p>
<p>
	On another note (somewhat related), I propose using a package.config/project.json file for binaries to prevent
	changes to library files (plus it will save space in the repo). Had one a long time ago but deleted the repo that was in it because
	it was too far gone (incorrect).
</p>
<p>The lead engineer (I'm assuming @ScottFromDerby) will have the final say.</p>
<p>This is just a proposal, what's actually going to be used should be formalized in the wiki or a CONTRIBUTING file. This is just to give some ideas.</p>

<h2>Naming</h2>
<p>For a lot of these, you can easily change them using <code>ctrl+alt+f</code>.</p>

<h3>Data Members</h3>
<p>
	I would prefer data members be in snake-case with a leading underscore (i.e., <code>some_var_</code>) as encoding type information is redundant.
	However, if the majority strongly desire Hungarian Notation that's fine too.
</p>

<h3>Methods</h3>
<ul>
	<li>For this one I'm not too sure on what we should do but I'll propose something any way.</li>
</ul>

<h4>Event Handlers</h4>
<ul>
	<li>Given my background, I propose we use Pascal case for these.</li>
	<li>An event handler for us is like the Message Handlers in my fork.</li>
</ul>
<h4>Other Member functions, internal functions(helpers), and global functions</h4>
<ul>
	<li>These should be in snake-case</li>
</ul>

<h3>Classes/Structs</h3>
<ul>
	<li>These should be in snake-case, we could make the first letter capital.</li>
	<li>In my fork I wrapped all the new stuff in a namespace (ra) but put a macro <code>_RA </code> to make it more consistent. It's defined like this: <code>#define _RA ::ra::</code></li>
</ul>

<h3>Enums</h3>
<ul>
	<li>Should be changed to "enum class", this prevents conflicts and disables implicit conversion to int.</li>
	<li>snake-case</li>
	<li>I made a helper function etoi (made an alias to_integral) to convert any enum to its underlying_type.</li>
         <li>I did put two concepts (type_traits) <code>is_equality_comparable</code> and <code>is_lessthan_comparable</code> to validate something is comparable it looks for the equality and lessthan operator. It will be important for some enums. If those validations pass in <code>static_assert</code> you can use <code>using namespace std::rel_ops</code> (suggest at function scope) to have the rest of the operators done for us. Some other operator overloads might be necessary as well but it's trivial.</li>
</ul>

<h2>Layout</h2>
<h3>More Formatting (not covered by .editorconfig)</h3>
<p>To check/uncheck, go to Tools->Options->Text Editor->C/C++->Formatting->(*something). *something will depend on what we're trying to do. Some of these might be checked/unchecked already.</p>
<p>To save time I'll just put a screen shot</p>

![image](https://user-images.githubusercontent.com/18649925/38270416-5911f276-3751-11e8-9b69-d56ab9607ea8.png)
![image](https://user-images.githubusercontent.com/18649925/38270448-72818f82-3751-11e8-8716-33f8e8715bfb.png)

<p>I'd suggest for everything besides multiline functions and long loops (the initialization part) put a brace on the same line with one space before it. </p>

<h3>Limit Macros</h3>
<h4>Unacceptable Uses</h4>
<ul>
	<li>Symbolic Constants (ironic)</li>
	<ul>
		<li>Sometimes a macro is the only solution; yet, if used for a global constant there is another way.</li>
		<li>That other way is use the keyword <code>constexpr</code>(wasn't fully implemented (still isn't, no <code>constexpr if</code>) by Microsoft until C++17 but did exist in C++14).</li>
		<ul>
			<li>
				Example: instead <code>#define SOME_STRING "a string"</code>, consider <code>inline constexpr const char* some_string{"a string"}</code>
			</li>
		</ul>
		<li><code>constexpr if</code>`is short for "constant expression" and can only be used on types that can be resolved at compile time.</li>
		<ul><li>Example: You can use constexpr on std::array but not std::vector, std::string, std::map, etc.</li></ul>
		<li>For the strings we should const char* since arrays aren't null terminated. In the Microsoft's version of the GSL they have something called <code>zcstring</code> which is a wrapper for <code>const char*</code> which is bounded.</li>
	</ul>
	<li>Aliasing</li>
	<ul>
		<li>For functions your can just use <code>std::function</code> with <code>std::bind</code>. (creates a function object instead of a pointer, which automatically deallocates).</li>
		<li>Another way is to use a function pointer alias.</li>
		<li> Example: <br />
			<code>int some_fn(char c, std::string str);</code><br/>
			<code>using some_fn_t = decltype(&some_fn); </code><br/>
			<code>const auto& another_fn{static_cast(some_fn_t)(some_fn)}; </code><br/>
                         It didn't like the angle brackets.
                 </li>
			<ul>
				<li>
					Now <code>another_fn</code> is an alias to <code>some_fn</code>; Did some extra steps because that's for overloads. Overloaded template functions needs parameter forwarding but we'll worry about that later.
				</li>
			</ul>			
		</li>		
		<li>
			For member functions, the same as the above but you have to provide an object. If it's in the same class using this, should be good enough.
		</li>
		<li>A better way to alias a type without declaring it is to use <code>using</code>. Instead of <code>typedef int some_type ;</code> consider <code>using some_type = int;</code>.</li>
</li>
	</ul>
</ul>
<h4>Acceptable uses</h4>
<ul>
	<li>Required by a dependency, such as <code>HANDLE_MSG</code>.</li>
	<li>Pretty much anything that is not used in execution (seldom few exceptions like above).</li>
</ul>

_Copied from original issue: RetroAchievements/RASuite#73_

**Comment by meleu** [comment]
_From @Jamiras on April 7, 2018 3:0_

I was disappointed by the fact that `.editorconfig` basically only handles tabs to spaces and indent levels, but it's a start. 

I agree with most of your suggestions, including all of the editor settings (which I believe are the default) and macro usages. 

I prefer `camelCase` over `snake_case` for variables and class fields, and `PascalCase` for class, enum, and method names (whether global or not). 

I don't really have a preference on whether or not class fields should be prefixed (i.e. `field` vs. `_field`), but I'm not fond of using a suffix (i.e. `field_`). 

The Hungarian variable names and much of the current formatting style are from before my time. If we wanted to change things to enforce a standardized style across the codebase, I don't think there would be much push back.

The codebase has been fairly stable for the last month or so, it seems like it would be a good time to attempt something like this. I'd recommend limiting the first pass to whitespace, and tackling names later.

**Comment by meleu** [comment]
_From @SyrianBallaS on April 9, 2018 19:4_

I'm honestly fine with anything as long as everyone's on the same page. Was just giving some insight based on my experience.

**Comment by SyrianBallaS** [comment]
Just a quick question about the namespaces. Did you want the sub-namespaces to hide implementation or expose it. If it's the later they should be `inline namespace`. Instead of doing `using ra::data::Achievement `you could just do using `using ra::Achievement` even though it's in another namespace. Otherwise it should just be a regular namespace.

**Comment by Jamiras** [comment]
From what I understand, inline namespaces are meant for versioning. If you put something in a namespace for any other reason, it shouldn't be inline. Namespaces should be used to group similar classes and keep them out of the current scope unless explicitly required. With proper segregation, it' takes more effort to create inter dependencies. Classes in `ra::data` shouldn't be talking directly to classes in `ra::ui`. As soon as you realize you have to explicitly reference the `ui` namespace, you'll take a moment to consider if it's the right thing to do.

**Comment by GameDragon2k** [comment]
Majority of these are in line with standard coding conventions. Don't have an issue with that for the most part. I do have comments on 6, 7, 11, and 14.

For 6 and 7, I personally prefer Hungarian notation. Just helps me to identify things faster and more concisely. 

As for 10 and 11, I agree completely with braces on separate lines, but I'm not too onboard with removing braces **only** if no branches require them. I would prefer to put braces where they are needed and exclude them when they aren't.
```
if (a==b)
{
    do_something();
    do_another();
}
else
    do_else();
```

14 is a big issue for me. Single-line ifs are something I use a lot depending on the length of the statement.

**Comment by Jamiras** [comment]
Since most of the code already uses Hungarian notation, I'm fine changing 6 and 7 to support that. 

I'm strongly against 14. Putting the `if` statement on the same line as the code to be executed reduces readability, couples the two statements in a diff if either changes, and makes it harder to put a breakpoint that's only hit when the condition is met. I will never do it, but if you feel that strongly about it, I'm fine with not requiring it.

Regarding 11: Symmetry improves readability, but I'm flexible.

I've drafted an updated proposal here: https://github.com/Jamiras/RASuite/blob/master/CONTRIBUTING.md

Are there any other changes or additions that are desired?

I'll look at creating a VS settings file and create a PR to globally reformat the code (whitespace only) next weekend.

**Comment by GameDragon2k** [comment]
14: From my pov, it increases readability, as it generally makes blocks smaller and requires less scrolling.

11: Flexible on this one as well, was just speaking what I typically do. My argument is mostly the same as my above statement. I just like smaller blocks.

**Comment by SyrianBallaS** [comment]
I'm fine with most of the proposal but I think the braces on control flow
statements should be on the same line and if one branch is a one liner it
shouldn't really need braces.

I'll try to tweak my prs to conform to this standard when I can.

On Apr 28, 2018 4:49 PM, "GameDragon2k" <notifications@github.com> wrote:

14: From my pov, it increases readability, as it generally makes blocks
smaller and requires less scrolling.

11: Flexible on this one as well, was just speaking what I typically do. My
argument is mostly the same as my above statement. I just like smaller
blocks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RetroAchievements/RAIntegration/issues/15#issuecomment-385204472>,
or mute the thread

**Comment by SyrianBallaS** [comment]
Not sure if it's common knowledge, but I think you should state that this repository should be a remote when forking when new stuff is added here so the forked repo can pull in the new changes.
