### ISSUE TITLE
New memory bookmarker feature: Pause if changed

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#151]
I would like to be able to be alerted when address I've selected in the memory bookmarker changes for debugging purposes.

This is already possible by making a dummy achievement and using ``Pause on Reset`` or ``Pause on Trigger``, so this would be considered a luxury QoL feature.

**Comment by kdecks** [comment]
## Mockups

### Mockup 1

Added on the right is "Pause on Change" button.
When the "Pause on Change" button is pressed the selected item is becomes light blue (color is irrelevant), demonstrating that it will pause when there is a value change in that address.

There is might be no conflict for colored "Freeze" and "Pause on Change" because you probably wouldn't want to watch an address for changes which you've frozen. (Maybe not; I know that it freeze is rewriting every frame after change not truly freezing.)

![image](https://user-images.githubusercontent.com/32706333/48309856-8745d080-e53f-11e8-93cb-9312f0e5737c.png)

### Mockup 2

Instead of using color there is a checkbox for each.

![image](https://user-images.githubusercontent.com/32706333/48309918-85c8d800-e540-11e8-82a5-4cb97aaaffa9.png)

### Current
![image](https://user-images.githubusercontent.com/32706333/48309644-f7eaee00-e53b-11e8-8ef4-88e1b75cc501.png)

**Comment by televandalist** [comment]
A history of changes for a bookmarked address would be nice, too.
