### ISSUE TITLE
New Achievement Flag: Reset Group

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#152]
I'm requesting a new achievement flag: ``Reset Group`` (or whatever you want to call it)

This would behave like a ``Reset If`` flag in terms of resetting and a ``Pause If`` flag in terms of group behavior.

The use cases are minimal but certainly I've seen a number of cases where it could be used in achievements that require more precision. 

The most recently example was in the concept "Pass the hockey pucks within 10 times within 10 seconds", with ``Reset Group`` this would become possible but having a ``Reset Group`` in 10 alts that each reset on a different second, every 10 seconds, and then the same condition in each that counts the number of passes.

I've thought of other use cases in the past, but nothing comes to mind at the moment. If I think of more, I'll add them.

----

Bonus points if it were possible to point to which group would be reset, but I think that's not realistic.

**Comment by kdecks** [comment]
Another use case for GroupReset or perhaps UnlockIf?

Concept
Do x task on n levels (not in a row)

Example: Clear 5 stages on Super Mario Bros where you don't kill anything.
In the core group, I could add a hit to my primary trigger, each time a stage ends. And a PauseIf with a hit each time there is a fail state.

What I can't do is unpause the PauseIf for starting a new stage without resetting the primary trigger's hits.

**Comment by kdecks** [comment]
Another use case for GroupReset

**Concept**
Lock out a player who has bound both players to the same input effectively doubling their damage OR letting them cheese ``~multi~`` sets.

The example below shows how a lockout could work using an alt.

**Alt 01**
1. GroupReset != On stage
`` //To prevent hits from accumulating out of game.``

2. AndNext P1 input != 0
``//This will prevent hits on the next condition when both player are doing nothing.``

3. PauseIf P1 input = P2 input, 1000 hits
``//If the player input is the same it will get hits. When the cap is reached the achievement will pause. So long as the player input isn't 0 and isn't mirrored for too long the achievement would process normally.``

4. GroupReset P1 input != P2 input
``//This would reset if the user input doesn't match. It also wouldn't mess up the core group.``

5. 1 = 1 ``//This will allow the achievement to trigger so long as as it's not locked up via the PauseIf``


---
Final Points:
- These conditions could also work in core if instead of GroupReset, An alternate would be a **targeted reset**, as in a condition that would only reset the hits on one condition instead of all conditions. Ideally this would process before PauseIf.

- Why this wouldn't work without a new flag: Other resets would interfere with this locking mechanic or the locking mechanic reset would interfere with the other normal trigger conditions.

- I recognize that there are certainly other ways to skin this cat.

**Comment by Jamiras** [comment]
I'm going to close this. I believe ResetNextIf as described in #512 is sufficient. 

For the example above:
```
ResetNextIf P1 input != P2 input
AndNext On stage
AndNext P1 input != 0
PauseIf P1 input = P2 input, 1000 hits
1 = 1
```
AndNext has higher priority than ResetNextIf, so the ResetNextIf applies to the PauseIf line. The secondary ResetGroup for not being "on stage" can be inverted as a requirement for the PauseIf by using AndNext.
