### ISSUE TITLE
New Feature: Achievement Sets Title (etc) Sorting

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#153]
![image](https://user-images.githubusercontent.com/32706333/47271747-3db62700-d539-11e8-8ffe-1d494444fe9a.png)

Specifically the ability to sort achievement sets alphanumerically by all fields of the header(?), as in ID/Title/Points/Author/Achieved? etc.

These fields are already clickable buttons, so I assume it was an intended feature not yet developed.

This is a QoL development feature and so it's low priority.

**Comment by Jamiras** [comment]
Duplicate of #8
