### ISSUE TITLE
New Feature: Mem Inspector: Bit switch buttons

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#154]
As a developer I would like to be able to easily switch individual bits for an 8-bit address. Many games hold data in single bits and being able to change them, for testing and debug, without needing to recalculate the 8-bit value would be rather convenient.

![image](https://user-images.githubusercontent.com/32706333/47314107-fba2e900-d5fd-11e8-9a94-54e1949689e1.png)

The enhancement here would be to turn the bits in the graphic above into buttons, which would poke 0→1 and 1→0 for the 8-bit address selected.

**Comment by Keltron3030** [comment]
I like this.😁

**Comment by DrPixelz** [comment]
Agreed. 👌
