### ISSUE TITLE
Adding noted addresses to bookmarks without changing windows

### ISSUE THREAD

**Issue by Keltron3030** [RetroAchievements/RAIntegration#156]
As a developer I would like a native drop-down of noted addresses for adding to bookmarks rather than having to switch to and select from the memory inspector drop down and then go back to bookmarks to add.

**Comment by Jamiras** [comment]
Possibly handled by #447. The "Add Bookmark" button is now present on the Memory Inspector dialog, so you can change addresses and push it without having to change active windows.

![image](https://user-images.githubusercontent.com/32680403/64932848-fd216500-d7fe-11e9-9127-e380d92f2de7.png)

**Comment by Keltron3030** [comment]
Works for me
