### ISSUE TITLE
For the memory inspector: Increase note code limit to 4000 characters

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#174]
Suggested by **MutaWarrior** in the dev channel on Discord:

As a developer who takes detailed notes, from time to time I'll reach the char limit, 511(?). Often detailed notes can be very useful for development (e.g. a list of the level id value and stage name).

I'm suggesting a limit of 4000, but this is a very flexible number.

I've never made a note that was more than 4000 characters, but I've gotten close. (see [Pokemon Snap](http://retroachievements.org/codenotes.php?g=10155). My work around is to add overflow into nearby addresses.)

-----------------------

I am unsure if this would require server changes.

**Comment by meleu** [comment]
On the server side the limit seems to be 1024 chars. At least that's what I think by looking at the CodeNotes table:

![codenotestable](https://user-images.githubusercontent.com/8508804/48310328-cd695700-e574-11e8-8d20-27d653c888cb.PNG)

Then I think the current limit is on RAIntegration. And maybe while sending the CodeNote to the server.

Explaining: I reached a limit of 492 chars while working on Shinobi 3, in the Code Note for the address `0x415A`. I was able to write a big CodeNote in the Memory Inspector dialog and saved it. Everything seemed to work fine, but when I load the code note again it wasn't complete.

**Comment by SyrianBallaS** [comment]
For the code note entry itself there really isn't a limit. Its arch dependent but the limit is quite large (from the toolkits perspective). The purpose is to avoid crashes, etc. 

Looking at the db above it seems that's where the limit is defined. So even if the toolkit allows you to write a large note, only that 1024 is sent to the db.

**Comment by SyrianBallaS** [comment]
We could warn users that their note is too big if it exceeds specification in the meantime.

**Comment by kdecks** [comment]
Certainly many special characters that count as more than one, emoji's for example.

**Comment by Jamiras** [comment]
Confirmed that the toolkit is truncating at 512 characters:
```
                    WCHAR sNewNoteWide[512];
                    GetDlgItemTextW(hDlg, IDC_RA_MEMSAVENOTE, sNewNoteWide, 512);
```
