### ISSUE TITLE
For Memory Inspector: New search value type: Initial Test Value

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#175]
Concept suggested by **Rimsala** in the Dev channel in Discord:

As a developer when searching for address/values often I will want to continually compare against my first search, instead of the other options **Last Known Value**, ``LKV``, **Given Value** ``GV``. The solution is proposed with a new value comparison type, **Initial Test Value** ``ITV``. There is something similar found in Cheat Engine.

### Use Case
I'm in room ID 1 and I want to know all the address/values that != the values of room ID 1 for room ID 2,3,4,5. I would need to I would need to make a savestates for ID 1 through 5.

Without ``ITV``
1. Load 1; New Test = ``LKV``
2. Load 2; != ``LKV``
3. Load 1; != ``LKV``
4. Load 3; != ``LKV``
5. Load 1; != ``LKV``
6. Load 4; != ``LKV``
7. Load 1; != ``LKV``
8. Load 5; != ``LKV``

With ``ITV``
1. Load 1; New Test = ``ITV`` or ``LKV`` (this first search would behave the same as if ``LKV``)
2. Load 2; != ``ITV``
3. Load 3; != ``ITV``
4. Load 4; != ``ITV``
5. Load 5; != ``ITV``

With ``ITV`` takes fewer steps and significantly decreases the chance of error.

-----

It seems that to implement this would take remembering the first filtered value, whether by ``ITV``, ``LKV`` or ``GV``. This may be already somewhat available given filter history.

----

### Mockup of possible appearance

![image](https://user-images.githubusercontent.com/32706333/48310334-fffe5a00-e54a-11e8-91d0-e3d3344ea3c2.png)

### Current appearance for comparison

![image](https://user-images.githubusercontent.com/32706333/48310343-202e1900-e54b-11e8-80a0-3d08c9353972.png)

**Comment by kdecks** [comment]
Here's another use case written by **Rimsala**

I want to find the ID of a room. But it's not an easy ID to guess (like 0, 1, etc). So I would create different save states for rooms A, B, C, and D. A fifth save state would also be in room A, but with many things changed (player health, enemies defeated, paused/unpaused, etc).

First I would search for an unknown value for slot 1 (room A). This becomes the "first scan".
Next I would search for a changed value in slot 2 (room B).
Next I would search for a changed value in slot 3 (room C).
Next I would search for a changed value in slot 4 (room D).
Next I would search for an unchanged value in slot 5 (room A with changes), compared to the "first scan".

The reason to do the room B-D searches is that some values will not change. We want to eliminate those, because the value we want (the room ID) did change.
However, many values can change when you change rooms, or the staus of a room. So looking for changed values isn't always that useful. That's why you want to make sure a value hasn't changed. You can do this by comparing to the first scan (which contains your original room ID).
When you do the last search, many things will have changed, and maybe only a few have stayed the same since the first scan. Only those values will remain.

**Comment by Jamiras** [comment]
I suspect the intent is "initial test value" (i.e. the value captured when hitting "New 8-bit test"). "First filtered value" suggests the value captured the first time "Filter" is hit.

**Comment by Jamiras** [comment]
The second use case can be done already, with a few extra steps
* Load slot 1, start new test
* Load slot 2, filter on !=
* Reload slot 1, filter on !=
* Load slot 3, filter on !=
* Reload slot 1, filter on !=
* Load slot 4, filter on !=
* Reload slot 1, filter on !=
* Load slot 5, filter on =

Each time slot 1 is reloaded and filtered on, we don't expect to find any new results, but it resets the search state for the next comparison.

**Comment by kdecks** [comment]
"First Filtered Value" never felt right. I've updated all the text in the opening post.
