### ISSUE TITLE
Dump of concepts

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#18]
_From @kdecks on April 8, 2018 5:49_

Anyone who wants to can dump incomplete ideas or ideas that have not yet been fleshed out, here, I'll be doing so. (Just as with anything just because I posted it does not mean I OWN the ideas, good ideas are living things that grow on their own!) Also these names are not important and could be called anything that's effectively descriptive.

Flags:
LockIf (single condition if met, will prevent further achievement processing for that group)
UnlockIf (single condition if met, will unlock the unlocked group above)
Achievement Pointers (an achievement or group that if true will add hits to another achievement, this is done somewhat with addhits and addsource)
ResetFirst (reset before pause) OR LatePause
ResetGroup
ResetTask (see task group below)

ALT group alts:
AND groups (All conditions one each group must be true at once)
Task Groups (Similar to AND groups. Once the conditions of a Task are met achievement processing stops, it cannot be paused or reset and remains TRUE. Once the Tasks and the Core group are true the achievement is activated. Can only be reset by a ResetTask)

Other:
Any kind of logic gates
Data sheet (a table of values are stored and retrieved by the achievement editor during the current session)
Offline data sheet (like above, but allows for values to be stored between sessions.) (Would probably need encryption or a hash check to prevent cheating.)

_Copied from original issue: RetroAchievements/RASuite#76_

**Comment by Jamiras** [comment]
`LockIf`: can be implemented using a `PauseIf` with a hit count. The "pause lock" can be reset via a `ResetIf` in an alt, or through an attached `ResetNextIf`.

`UnlockIf`: handled by resetting the pause lock as described above

`ResetFirst`/`ResetGroup`: As discussed in #512, being able to reset specific subitems is preferable as it allows the finest level of control over what is being reset.

`AND groups`: sounds like an `AndNext` chain - probably with an attached hit counter, or the `AndNext`s are redundant.

`Achievement Pointers`/`TaskGroups`: You can use `AndNext` chains to build subclauses for tallying complex ideas. Achievement Pointers might also be handled by the `Data Sheet` concept.

`Data sheet`/`Offline data sheet`: I believe this is the same idea as #478, where the offline data sheet is often referred to as "multi-session" data.

`ResetTask`: `ResetNextIf` will reset all hits in an `AndNext` chain.
