### ISSUE TITLE
Color highlights for Achievement Editor

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#180]
As a developer I want to be able to easily read the state of my active achievement at a glance. Adding optional color feedback will make this possible.

### Some current inconveniences it solves
- There is no way to see that a specific requirement is being reset without checking the address in the memory inspector.
- It's not possible to see if a a condition with hits, full, is still true.
- Sometimes it's not clear if an achievement was reset, paused, etc.
- Should help inexperienced developers understand how achievements are processed more intuitively.

### Coloring
(these colors could be adjusted, but I feel they are informative, and I prefer the detail. Seeing them in motion would help one decide if the colors are fitting.)

- **Red:** A ResetIf condition is actively resetting.
**Lighter Red:** A reset condition with hits it getting hit.
- **Yellow:** A PauseIf condition is actively pausing.
**Lighter Yellow:** A PauseIf condition with hits is getting hits.
- **Green:** A normal condition is actively getting hits
- **Blue:** A Normal condition has had all hits.
**Lighter Blue:**  A normal condition has had some hits.
- **Grey**: Add hits / Add Source / Sub Source. This show that they are not directly involved with processing.

### Some if, thens and whens
- If a condition is paused, **yellow**, then **green** and **red** will not be seen anywhere else. This will help illustrate pause behavior.
- If a condition with 0 hits or >0 hits is actively true, it will be green. 
- When conditions with hits are no longer actively true, **green**, they will become **blue**.
- When **blue** is reset it will become white.
- If all the normal conditions become green or blue the achievement will trigger.

### Mockup Alt
![image](https://user-images.githubusercontent.com/32706333/48312516-27661e80-e56d-11e8-87e7-a0f473460f53.png)
- Note that this is only to give a visual impression, the conditions colors are not being met.
- Notice hits for light/dark blue
- Note the show highlights button above Show Decimal Values. This coloring is optional.

### Mockup Alt
![image](https://user-images.githubusercontent.com/32706333/48312525-4369c000-e56d-11e8-9cf7-b280d2c7c0e9.png)
- This is without a second blue color.
- **Blue**: A normal condition had had some or all of its hits.

### Current for Comparison
![image](https://user-images.githubusercontent.com/32706333/48312320-27185400-e56a-11e8-8cd5-236e575a8912.png)

**Comment by Keltron3030** [comment]
Very nice work kdecks.  One additional suggestion to add visibility in the inspector would be to have a "read only" column on the far right which shows the current value for the one or two referenced memories.  For example if there's a comparison for two memory address references the field will show from left to right [0x45; 0x28].  If only one address is referenced, [ ---- ; 0x28] or [0x45; ---- ] depending on which side of the operator the memory address is located.  This would also work for Delta comparisons so the field would should the current value and the previous frame's value in the same manner.

**Comment by kdecks** [comment]
That's a solid idea, and should be split into it's own issue.

**Comment by Keltron3030** [comment]
Ok, I'll look to add a separate issue I'm the near future.  The Delta part is probably not that informative since the previous frame is almost always going to be the same as current frame at a glance.

**Comment by Jamiras** [comment]
When this was first proposed, I mentioned concerns about the frequency of the colors changing. I suppose that's up to the user's discretion given the checkbox to enable the feature.

I recommend making the enabled property behave like "pause on reset" - i.e. per achievement, off by default, and not persisted across sessions.

**Comment by Jamiras** [comment]
I have implemented this (or at least something very similar) in #699
