### ISSUE TITLE
To help development, hide Overlay during frame advance, RAVBA

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#181]
Frame advance is a very useful tool for precision development. As a developer, to make full use of frame advance I need to be able to see what is happening on the game display. Unfortunately RAVBA's overlay hides covers the display during frame advance. Please remove it if possible.

**Comment by Jamiras** [comment]
I believe this is an emulator issue, not a toolkit one. Will leave here until investigated.

**Comment by kdecks** [comment]
It appears to be resolved here: https://github.com/RetroAchievements/RAEmus/pull/19

Also, I put this bug report into the wrong repository. Closing.
