### ISSUE TITLE
Bug RASnes9x, frame advance keypress does not work

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#183]
At least in my tests for RASNES9x 0.025, during softcore, the frame advance keyboard keypress does not work, regardless of the key it is bound to. The frame advance still DOES work from the toolbar, so this is a minor annoyance, but fixing this bug would still make achievement development for RASnes9x a smoother ride.

**Comment by Jamiras** [comment]
I did not experience this issue using the default frame advance key (backslash). In fact, it also seemed to work in hardcore mode - will fix that ASAP.

**Comment by Jamiras** [comment]
Also, this is an emulator issue, not a toolkit issue.

**Comment by kdecks** [comment]
In addition to being an emulator issue it's a localized (just me) bug.
