### ISSUE TITLE
Enhancement for the leaderboard value field; turning a non-zero number into one

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#184]
As a developer who loves making leaderboards I would like a means to turn any **non-zero value**, for the ``Value`` field into **one**.

This is needed only occasionally, but often without it sacrifices in design must be made. 

### Use Case
Recently I made some leaderboards for Metroid II, the weapon address stores the beam as:
0: No beam
1: Ice
2: Wave
3: Spazer
4: Plasma

I needed a way to count "had beam weapon", as a single unchanged value, but have no means to do so. This is one of a handful of other cases where I had to abandon my original intent.

### Two possible solutions
1. Add support for exponents in value. As x^0 = 1.
    - Exponents would also value in other uncommon cases.
2. Add a special operator that turns any non-zero value into 1.
    (And still allowed that number to be multiplied by any value.)

**Comment by Jamiras** [comment]
I believe this can be accomplished using a Measured/MeasuredIf construct.
```
Q:x!=0_M:y
```
The overall value `y` would only be captured if `x` was not zero. And you can still do the multiplication if desired:
```
Q:x!=0_M:y*1.5
```
