### ISSUE TITLE
Hardcore Suspend. Single Restorable save that ends emulation on save.

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#185]
As a hardcore player I would like to be able to ``suspend`` my current hardcore session, (which would save and end the game), turn off my emulator and then later restore the session and continue playing in hardcore.

This sounds like a difficult problem. I have no idea how realistic of a request this is, and the implementation would likely vary from emulator to emulator. But, the fact that hit counts can be saved in softcore saves makes this feel more possible than ever before.

**Comment by Jamiras** [comment]
The problem isn't any more difficult than being able to create a savestate from the toolkit. The problem is that this isn't exactly "hardcore".

**Comment by Jamiras** [comment]
You also have to consider abuse. What's to prevent someone from "suspending" their session just before something difficult, and externally backing up the suspended state so they can continuously restore it and attempt the difficult thing again? It's just a slower, more complex save state.
