### ISSUE TITLE
Better Ticket reporting, new fields and data snapshots

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#187]
As suggested by **MutaWarrior** in the devs channel in Discord.

As a member of the admin team I want for the developers to have as easy a time as possible resolving tickets:

The enhancement idea is that when a ticket is submitted a snapshot of the current hitcounts for the achievement in question would be included as part of the ticket report. This could possibly be integrated into @meleu's recent memory inspector logic display update for tickets.

- The snapshot may vary in usefulness depending on how long after the ``didn't trigger`` type of ticket is reported.

I do not know how much this issue is a hybrid-web/integration issue. Regardless, anything that can help developers get a better clue to what is going wrong is for the best.

**Comment by Jamiras** [comment]
Related to https://github.com/RetroAchievements/RAWeb/issues/119.

As suggested, the data would be inaccurate for "didn't trigger" tickets, and may even be misleading. For example, a failed damageless boss achievement may be entirely reset when the player advances to the next stage, or a pre-condition may be reactivated after the boss is defeated.

And for "triggered at the wrong time" tickets, you should have a pretty good idea of the values as the achievement did trigger.

**Comment by JuliaWolska** [comment]
I think such log could still be potentially very usefull, especially for achievements, which require multiple checkpoints in a game with more chaotic and bigger memory, in a big system which could get affected in countless ways, with bigger chance for hard to find, random malfunction (RAP64). Something like this shouldn't be used as an evidence for the achievement being bugged, but in case of searching potential loopholes, when any piece of information like this could help you.

**Comment by kdecks** [comment]
## Redraft of "Better Ticket Reports"

> Response to feedback here posted by @Jamiras and discussions and thoughts I've had since. Shoutout to @JuliaWolska for helpful feedback.
> I'd like to highlight that I feel like below is a big undertaking, and I'm not sure if it's reasonable. But perhaps we can take some aspects of it into actual development.
> Also integrated ideas from https://github.com/RetroAchievements/RAWeb/issues/119, suggested by @magusLOGS


## Primary Changes to "Report Broken Achievements" (Front & Backend)
- Rename RetroAchievements toolbar item and window from "Report Broken Achievement" to "Report Achievement problem"
- Reword and add Problem Types; re-titled``Triggered at Wrong Time`` and ``Didn't Trigger at all`` to something shorter. ``False Trigger`` / ``Absent Trigger``. (names not important).
   - ``False Trigger``
   - ``Absent Trigger``
   - ``Typo``
   - ``Description unclear``
- Remove the introduction explanation.
- Add contextual question for each type of report.
- Add contextual file / uploads.
- Add contextual backend data snapshots:

**Collect contextual data snapshots:** ``False Triggers`` and ``Absent Triggers`` (invisible to reporter)
- Snapshot of ticket hits. 
   - Purpose for ``False Trigger``: To show which alt may have triggered or for normal reqs with (0) hits asked, the number of current hits since last reset could be informative. (not very)
   - Purpose for ``Absent Trigger``: To check which conditions have and have not been met.
- Snapshot of current **values for all conditions** in the ticketed achievement(s).
   - Purpose for both: To help give context and current player states, compared with expected trigger point, and to help give a clue about what might have gone wrong, and.)
- Snapshot of ``Rich Presence``. 
   - Purpose for both: To help give context and verify accuracy of other snapshot's data; to check where the player is currently game in relation to the ticket hits snapshot.

### False Trigger, mock-up appearance and questions
![image](https://user-images.githubusercontent.com/32706333/48594827-7dd9b100-e90f-11e8-8b7c-14d6b87c1df1.png)
What was happening on screen when this achievement triggered? 
(What game screen or stage were you on? What actions were you taking? Tell us any related details you think might be relevant: Lives, hp, items equipped, score, places you've been, anything unusual you did, etc.)
``[Response box]``

How much time has passed in game since the Absent Trigger? Are you on the same screen as when you reported it?
``[Response box]``

Please do any of the following that might be helpful for the developer to address the problem:
- (optional) Upload screenshot... ``[ Upload button ]`` **OR** Paste url of game screenshot ``[Response box]`` ``[Submit Button]``
- (optional) Upload game save state ``[ Upload button ]``
- (optional) Upload game battery save file ``[ Upload button ]``

### Collect the following game data (hidden from reporter)
- Snapshot of ticket hits. (To show which alt may have triggered or for normal reqs with (0) hits asked, the number of current hits since last reset could be informative. (not very)
- Snapshot of Rich Presence. (To help give context, and check where the player is in game in relation to the ticket hits snapshot.)
- Snapshot of current values for all conditions in the achievement. (To help give context and to help give a clue about what might have gone wrong, and possibly indicate the current position of the play relative to the trigger point.)

----
### Absent Trigger
What requirements did you complete?
``[Response box]``
What led up to you earning this achievement?
(What in game settings have you chosen? Paths you have taken? How long have you been playing? How many reattempts have you taken since the last game reset? Any other details?
``[Response box]``
How much time has passed in game since the Absent Trigger? Are you on the same screen as when you reported it?
``[Response box]``

Please do any of the following that might be helpful for the developer to address the problem:
- (optional) Upload screenshot... ``[ Upload button ]`` **OR** Paste url of game screenshot ``[Response box]`` ``[Submit Button]``
- (optional) Upload game save state ``[ Upload button ]``
- (optional) Upload game battery save file ``[ Upload button ]``

----
### Typo in title or description
What is the typo, and what do you think it should say?
``[Response box]``

----
### Description is unclear or confusing, mock-up appearance and questions
![image](https://user-images.githubusercontent.com/32706333/48596151-ed05d400-e914-11e8-8e1d-172652d02739.png)
What is unclear or confusing about the description?
``[Response box]``
What is your guess for what you're expected to do?
``[Response box]``

### Current window for reference
![image](https://user-images.githubusercontent.com/32706333/48572317-5c080c00-e8c6-11e8-9068-2024d8999a8b.png)

**Comment by kdecks** [comment]
Another related idea is to integrate manual unlock requests into tickets for "Did not trigger at all" types.
