### ISSUE TITLE
Make RALib Single Input by default

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAIntegration#192]
Requesting that Port 1 is the only active port by default. 

I often need to change multiple ports to none and/or unassigned every time a core (and sometimes a game) is loaded. I only have one XInput Controller, but RALib initially wants that one controller to control several ports. 

Normally it wouldn't be that big of a deal, but I have noticed that FB Alpha and PC Engine CD games don't agree with this at all and will often hang or crash RALib if an input setting is adjusted. This is especially frustrating since changing games for these cores require RALib to be shut down and restarted every time a game is switched. 

By the way, I just created a GitHub account a few minutes ago, so feel free to call me out if I'm not doing this properly.

**Comment by Jamiras** [comment]
This sounds like an RALibRetro issue and should be created in that repository: https://github.com/RetroAchievements/RALibretro/issues
