### ISSUE TITLE
Endianess Identifiers

### ISSUE THREAD

**Issue by Keltron3030** [RetroAchievements/RAIntegration#200]
As a developer I'd like additional memory address Identifiers including big-endian (BE).  We currently have bit0-7, upper4, lower4, 8-bit, 16-bit, 32-bit.

I would like to also have 24-bit, 24-bit (BE), 16-bit(BE), 32-bit(BE).

The typical use case is when trying to award achievements for score increases.  Since the default mem identifiers are (LE), the developer cannot easily use addsource/subsource to look for (BCD) score increases without having to deal with over-flow, e.g. 9 rolling over to 0.

For example, if I want to get a hit each time the 16-bit score increases by 20.  So, 0090 + 0020 goes to 0110.  With the default as (LE) 9000 goes to 1001 which is not easy to code for without using many alt conditions.

I suppose we'd also need a check box to designate expected values as BCD (binary coded decimal).

I apologize if this is difficult to follow.  Maybe someone can explain better.

**Comment by Jamiras** [comment]
24-bit support is being added via #457
