### ISSUE TITLE
Reset achieved status button and condition

### ISSUE THREAD

**Issue by salvadorc17** [RetroAchievements/RAIntegration#217]
This button is now missing in the toolset, it was present in the past and allowed to reset online achievements tampered, this allow to test those again without need to reset game.

![image](https://user-images.githubusercontent.com/13541889/50379944-f9bdcc00-0626-11e9-9501-7db63d870999.png)

**Comment by salvadorc17** [comment]
Dont think achieved is same as activated, unless this button does both at same time, i want to reset tampered cheevos for testing conditions over again.

**Comment by Jamiras** [comment]
The old button never actually reset the achievement. Pushing the button simply enabled the achievement for processing, which is exactly what the "Activate Selected" button does.

**Comment by salvadorc17** [comment]
So this feature was added in my emulators, and does it reseted properly, you can consider that reseted achieved can send info to server.

**Comment by Jamiras** [comment]
I'm not sure I'm understanding your last statement, but if you reactivate an achievement, when it triggers, it will notify the server and the server will respond with "error, user already has this achievement" or something similar because it's an entirely client-side feature.

**Comment by salvadorc17** [comment]
Ok, but the request is to allow client reset achievement manually from toolset, without need to use the site.

**Comment by Jamiras** [comment]
Then API work is needed. The button that you claims used to do that _never did that_.

**Comment by salvadorc17** [comment]
Ok, i suppose closing the issue now.
