### ISSUE TITLE
trigger achievements only when the condition set becomes true after being false

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#238]
This feature request is a result of the discussion that happened here: RetroAchievements/RALibretro#52

The main goal here is to increase compatibility between all RA client emulators.

To avoid false triggering due to non-standardized initialization of the RAM (different behavior among various emulators), I suggest adding a logic responsible to trigger the achievements only when they become true after being false.

As pointed by @leiradel this is the RetroArch's behavior.
Reference: https://github.com/libretro/RetroArch/blob/c2047c8c04818715cf606249db630a3836619aa2/cheevos/cheevos.c#L1630

And according to him, `rc_reset_trigger` can be used to accomplish this.

**Comment by rzumer** [comment]
This would not solve every potential issue caused by making wrong assumptions on the contents of uninitialized RAM, but it seems like a good change to reduce the likelihood of such errors triggering unlocks on load. Either way, the implementations should match.

**Comment by Jamiras** [comment]
It's actually the `last` flag (line 1634) that provides this behavior in RetroArch. 

I believe this is a valid alternative to the "100 frames" solution and will be implementing it as such. If an achievement is active on game load, it will be ignored until it becomes inactive, at which point it will be allowed to trigger in the future. If any achievements would trigger in the first frame, they will be ignored, and all other achievements will become activate for the second frame. This effectively sets the "100 frames" delay to "1 frame" for most achievements and "as many frames as necessary" for any achievements that are triggered by the uninitialized memory.

Similarly, on reset, all active achievements will have their HitCounts reset and be temporarily deactivated for "1 frame" or "as many frames as necessary" to prevent triggering during the reset process.

It also provides consistency between the implementations.
