### ISSUE TITLE
Requirements Gathering (really need input)

### ISSUE THREAD

**Issue by SyrianBallaS** [RetroAchievements/RAIntegration#25]
_I'm just going to work on other stuff and leave this alone for awhile._

_**Edit: Since there aren't really any features being added/removed there won't be an SRS, but will still like some feedback.**_

OK, so it came to my attention that there are several aspects of the project that I either overlooked or had no idea what was required of them. This issue will comprise a series a of questions based on #19 Issue. This may seem overblown for an open-source project but my engineering process here has come into question. So resolve that, I will try do things the "_right_" way, in accordance to process best-practices.

**Maybe in the future**
I currently do not have access to set-up a GitHub project on this repository so something reflecting this will be in my fork for organization purposes. 

Once the requirements have been gathered I will formalize it into a **SRS** (Software Requirements Specification) and post it here for review (I don't access to request reviews, add labels, etc.). It will also be in my fork in a "**docs**" folder but will not be included in pull requests.

**Comment by SyrianBallaS** [comment]
<p>These are really all the questions I have for now, if there's more requirements please list them.</p>


<section>
<h1>General Questions</h1>
<h2>Libraries</h2>
<ul>
	<li>
		Would you rather keep libraries up-to-date (as much as the requirements allow) or keep them how they are?
	</li>
</ul>
<h2>Complexity</h2>
<ul>
	<li>
		Space-Time Trade-off
		<li>
			What is more important for this application, the efficiency of execution or the space of the executables?
		</li>
	</li>
	<li>
		Simplicity
		<li>
			Would you be willing to find something simpler more appealing or rather keep things the same? 
		</li>
	</li>
</ul>
<h2>SDL (Software Development Life-cycle)</h2>
<ul>
	<li>Is constantly improving software important to you, or would you rather have it stay the same?</li>
	<li>Which paradigm seems more appealing to you, AGILE or Waterfall? (You don't have to answer if you don't know what they are).</li>
</ul>
</section>

<section>
<h1>Specific</h1>
<h2>Strings</h2>
<ul><li>What are the required character encodings?</li></ul>

<h2>Re-usability</h2>
<ul>
	<li>Should classes/types be as abstract/reusable as possible or just copy and paste and change a few lines?</li>
</ul>

<h2>Availability</h2>
<ul>
	<li>
		Should modeless dialogs be available all at the same time in the same level (Z-Order) or should only one be allowed?
	</li>
</ul>

<h2>Security/Safety</h2>
<ul>
	<li>Are memory leaks an issue? (<i>I think they are, RASnes9x...</i>)</li>
	<li>Is it important to handle errors/exceptions or just let them fail silently?</li>
        <li>Is there any places in the application that are especially error-prone/security-risk?</li>
</ul>

<h2>Standards</h2>
<ul>
	<li>Is the ISO C/C++ standard important?</li>
	<li>Should standards be followed?</li>
        <li>What are the standards for this project?</li>
</ul>


</section>

**Comment by coczero** [comment]
Libraries
- Always up to date imo. There is a reason software gets updated.

Complexity
- STTO: Efficency is way more important. Modern storage devices are so big, that size of files almost doesn't matter anymore. Although of course it can affect performance if files get too big.
- Simplicity: Yes.

SDL:
- Constantly improving: Yes, the software world is changing all the time and adaption is better than staying behind.
- AGILE all the way.

Re-Usability: yes as abstract and reusable as possible, but in a manner where it makes sence. Don't try to make EVERYTHING abstract and reusable.

Availability: Im fine with multiple.

Security/Safety:
- Yes, memory leaks are an issue
- Errors should be handled with exceptions so we can at least log them.
- A lot I think. No specifics tho.

Standards:
- Yes we should follow standards.

**Comment by SyrianBallaS** [comment]
I'm not sure if this should stay open or not. Most of this seems like common sense for anyone with an engineering background but just wanted to see everyone's take on it. Due to slight controversies and misunderstandings.
