### ISSUE TITLE
Achievements seemingly cannot be saved unless game is active

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#272]
I just experienced an error message saying that I did not have any game loaded while trying to save local achievements. I had just loaded the title, so I assume it is due to the fact that I was in a paused state, and the title was considered inactive.

Attempting to activate an achievement while in a paused state also does not work.

I guess that this is all based on `GameIsActive()` which I set to false on pause.

**Comment by rzumer** [comment]
I guess it is not an issue with the toolkit, but rather with my misinterpretation of the purpose of `GameIsActive()`; leaving open in case it can be clarified in the interface, but I guess it can be closed as invalid otherwise.

**Comment by Jamiras** [comment]
I'm slowing replacing `GameIsActive` checks with the internal logic that indicates a game has been loaded, which is a much better indicator as it also handles when a hash doesn't resolve. Most of the emulators just always return true.

Closing based on your comments.
