### ISSUE TITLE
Frequent crashes while using RAIntegration

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#273]
I am experiencing frequent crashes lately, especially with the current master version linked to `RAppleWin`. Specifically, the whole application has crashed while doing the following, all within a few hours of testing, using the latest master version:

* Opening/using the memory viewer
* Applying a filter in the memory viewer - quite a few times
* Attempting to open a file select menu
  * Once via the "Upload badge" button in the achievement editor
  * Once via a key bound to select a save state to load
* ~Loading a save state (with memory viewer and/or achievement dialogs open) - many times, it seems almost a 75/25 chance of crashing~
* Just leaving the game and toolkit dialog windows opened for a few minutes

I have also crashed two or three times using `RAQUASI88` in the last few weeks, but it is not nearly as bad.

It seems to me that stability has decreased lately, but it could just be because I have been using the toolkit more heavily. It could be that the emulators I am using have trouble dealing with the increased load of processing the RA features.

I will try to debug `RAppleWin` to figure out if it is due to errors in the upstream code that just happened to cause problems with the addition of `RAIntegration`, but in the meantime I thought I would raise the stability issues I have encountered in case they can be of reference. Without the RetroAchievements features I have not experienced any crashes.

**Comment by Jamiras** [comment]
The only one of these I could reproduce was loading a save state, which threw an unhandled exception in the RAppleWin code, not the toolkit:

> Unhandled exception at 0x6E697765 (MMDevAPI.dll) in RAppleWin.exe: 0xC00001A5: An invalid exception handler routine has been detected (parameters: 0x00000002). occurred

![image](https://user-images.githubusercontent.com/32680403/51580285-36c4ea80-1e81-11e9-9e3b-77b130d33500.png)

Since you know how to build the dll (and the application), I recommend building both in DEBUG mode and running in the debugger so you can capture the stack trace. If you can provide a stack trace indicating a problem in the toolkit, I'll gladly look at it.

Otherwise, I'm going to assume the other crashes are code within the application as well.

**Comment by rzumer** [comment]
I have gone just far enough in debugging to have notice that, but as for the other crashes it is not easy to determine where the problem comes from unless debugging for extended periods of time; the most common crash that I have experienced on multiple emulators implementing `RAIntegration` is on filtering in the memory viewer, so it might be worth taking a look at that if anything. I agree it is likely that most of the `RAppleWin` crashes I have experienced are due to issues in the emulator itself though. Will update as I look into it.

**Comment by rzumer** [comment]
I have eliminated the cause of save-state-related crashes from `RAppleWin`, which clears up the large majority of the crashes I have experienced recently, though not all - I will keep using it in debug mode for a bit and see if I can isolate any other issue.
