### ISSUE TITLE
Clear the pop-up queue for unloaded titles

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#279]
When loading many titles (or even the same title) multiple times very fast, the overlay pop-up queue can take a while to clear up, repeating the same messages over and over. I think it would be good to simply clear the queue when clearing the game information.

**Comment by Jamiras** [comment]
My gut says this isn't necessary.

A typical user isn't going to "load many titles multiple times very fast", and if we do clear out the queue when they switch titles, they may miss out on an important message that is queued.  

However, we do already do it on user logout, so it wouldn't be unreasonable.

**Comment by rzumer** [comment]
I can see it causing issues in a few situations so I agree, but if it is possible to identify the messages how about pruning the ones that only show up on load (leaderboard, game info, etc.)?

**Comment by Jamiras** [comment]
This was implemented as part of #382: https://github.com/RetroAchievements/RAIntegration/pull/382/files#diff-08af573baa45c0c466cbd6ec63421618R133
