### ISSUE TITLE
x64 build

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#284]
I would like to be able to link with x64 build of emulators.

This requires an x64 build configuration for `RAIntegration` and the ability to fetch the correct build from the server on update.

**Comment by SyrianBallaS** [comment]
I've actually wanted to do something like this for a while. Anything that works on x64 will work on a x86 build. X64 is just short for x86_64. 

Shouldn't be too tough as I already did most of the work via code smell correction (not done yet, the code suffers from range bugs like buffer overrun) prs but will still need a little of work.
