### ISSUE TITLE
Text input does not work when linking with SDL1 application

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#287]
SDL1 will not handle text input automatically, which means that `RAIntegration` should provide its own event handlers for filling out text boxes, since events cannot be propagated from the client's end.

Keyboard event handlers are processed correctly, because navigation in the memory inspector, for example, works as expected.

While I have not found out anything about this issue in my research, I don't think this can be solved without change to `RAIntegration`, because the key events "belong" to it, i.e. I cannot intercept events on sub-windows with the client application.

**Comment by rzumer** [comment]
Example: https://github.com/rzumer/oricutron/tree/cheevos (use the `RAOricutron.sln` solution in the `msvc\MSVC2017` directory)

**Comment by Jamiras** [comment]
This is also a known issue for Allegro. 

The message loop must call `TranslateMessage` to convert the `WM_KEYDOWN` messages to `WM_CHAR` messages. It's not something we can really do anything about in our code.

https://docs.microsoft.com/en-us/windows/win32/winmsg/using-messages-and-message-queues
> If your application must obtain character input from the user, include the TranslateMessage function in the loop.

See also #758. A customized message loop is required to support tabbing between fields.
