### ISSUE TITLE
Mouse cursor moves to the corner of the screen when trying to drag-select

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#291]
I can reproduce this consistently with achievement 71163, when the condition list scroll bar is moved down at all. When clicking and dragging in the Achievement Editor window the mouse cursor is moved all the way to the top-left corner of the screen, making it impossible to select what I want.

**Comment by Jamiras** [comment]
Must be something on your end.
[2019-01-30 07-26-13.zip](https://github.com/RetroAchievements/RAIntegration/files/2812954/2019-01-30.07-26-13.zip)

I'm not aware of anything in the DLL that sets the cursor location. Grepping the code for "cursor" finds 11 matches. 8 in comments, two GetCursorPos calls in the achievement editor tooltip code, and a LoadCursor call for the memory viewer.

**Comment by rzumer** [comment]
After updating to the same build reported to fix the issue for 7-zip, and recompiling both RAIntegration and QUASI88, the issue still persists. I can move the issue to `RAEmus` since it does not seem related to Integration, but I would like to identify a solution that does not involve installing a third-party patch if possible.
