### ISSUE TITLE
Status code 12007 when updating the toolkit while it exists

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#297]
I was getting this error on attempting an update from 0.74 to 0.75 using WINE and RAQUASI88.

**Comment by meleu** [comment]
I got 12005 on attempting to update 0.74 to 0.75 using VirtualBox+Windows7 and RALibretro, also with RANes.

![error](https://user-images.githubusercontent.com/8508804/52263403-3a8f4d00-2916-11e9-8b3c-7f40c34a1f1d.png)

Worked fine when I deleted the old RA_Integration and launched the emulator again.

**Comment by rzumer** [comment]
12005 is `ERROR_INTERNET_INVALID_URL` and 12007 is `ERROR_INTERNET_NAME_NOT_RESOLVED`.

**Comment by Jamiras** [comment]
12007 usually occurs when a network hiccup occurs trying to perform the DNS lookup. It's in the list of automatic retry codes _within_ the DLL. The download logic for the DLL is not in the DLL, so doesn't have any retry logic. 12007 occasionally happens with the older DLLs as well.

12005 indicates the hostname is not parseable. I have never seen that.

Regarding WINE: I don't plan to support this, if it works, great, if not, well, tough luck. There's a lot more important stuff to be done first.
