### ISSUE TITLE
ChangesTo operator

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#3]
_From @Jamiras on March 21, 2018 14:39_

As a developer, I would like to track the number of times a value changes to a specific value. To do this currently, I usually write an achievement like "value = X HitCount N and PauseIf delta(value) != X", but this pauses the entire condition group while the "delta(value) != X" clause is true, preventing it from being reset.

What I'd really like is "value ChangesTo X HitCount N" where ChangesTo evaluates as "= X and delta != X". Then I could use it like any other condition and not have to worry about the achievement being paused. 

_Copied from original issue: RetroAchievements/RASuite#56_

**Comment by meleu** [comment]
_From @Jamiras on March 21, 2018 15:46_

May not be necessary if we implement `AndNext` as suggested in #59. Then you'd just do something like:
```
AndNext value = X
delta value != X HitCount N
```

**Comment by Jamiras** [comment]
can be handled using AndNext. closing.
