### ISSUE TITLE
Tickets generated from RAI do not include the emulator name

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#313]
[Example](https://retroachievements.org/ticketmanager.php?i=17411).

While in this case there is only one emulator, it might change in the future. I am not sure if other platforms also suffer from this issue.

**Comment by Jamiras** [comment]
Assuming the running emulator is the emulator where the issue occurred is dangerous. Prior to having a way to submit tickets from the website, RetroArch players would load the standalone emulator just to submit tickets.

All requests coming from the integration include a `User-Agent` header indicating not only the emulator, but also the version of it, and the version of the DLL, and while it wouldn't be difficult to append this to the comment, it would be much better to have the server code store handle it. It could append it to the comment, or store it in a separate field. 

However, as stated above, the tickets may not be submitted from the emulator where the problem occurs. In addition to RetroArch not having the ability to submit a ticket, a user may try both RALibRetro and the standalone alternative before submitting a ticket, and the error could have occurred in either or both. It would be more appropriate to capture the `User-Agent` information for each unlock, and associate that data to the ticket. For incorrect unlocks, you'd know exactly where the unlock came from, and for did not trigger, you could infer from other achievements the player did earn.
