### ISSUE TITLE
Block unlocks when adding empty alts

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#325]
When adding an alt to an activated achievement (in core) it will be unlocked automatically. It should be marked as modified instead and block activation.

**Comment by Jamiras** [comment]
This has been fixed. I believe by #330:
> * mark achievement as modified in list when adding or removing groups

In any case, it's only possible to do this if everything in the core group is true. It's not like a user can just open a game and unlock everything by doing this at the title screen.
