### ISSUE TITLE
Memory Inspector - searching for a specific address it take you to its hexadecimal counterpart

### ISSUE THREAD

**Issue by Altomar79** [RetroAchievements/RAIntegration#331]
I'm not sure if someone already mention it but i wasn't able to find any reference for this issue.

In memory inspector when i type a specific address in "Watching" if the address start with a number
instead of taking me to that address it goes to hexadecimal counterpart. For example typing 9450
it goes to 24ea instead which is the hex of 9450. Work only if i type the address as 0x9450.
If the address start with a letter then there no problem. It take you to the correct one.

![memory](https://user-images.githubusercontent.com/36702297/54071952-a7329a00-427c-11e9-89ae-5828b758f376.jpg)

**Comment by Jamiras** [comment]
The code that parses the address is also being used in other areas to parse things that can be either hex or dec. Decimal is assumed unless the string starts with "0x" or fails to parse as decimal. I believe it is safe to assume that all addresses will be in hex, so will modify the code appropriately.
