### ISSUE TITLE
Cannot create new local achievements despite a linked game being loaded

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#338]
With the current master, after loading a title (with `RA_OnLoadNewRom()`), all seems to work correctly (linking, opening game page, getting checksum, ID display in the achievement window, etc.), but when attempting to create a new local achievement, an error message pops up and claims that no ROM is loaded.

![image](https://user-images.githubusercontent.com/7488362/54483325-a58e4680-4827-11e9-8535-402cb924a678.png)

**Comment by Jamiras** [comment]
In all places where this error is displayed, it's checking `GameContext.GameId()`, which is also what is used for "opening game page". Can you attach the `RALog.txt` associated to this behavior?

**Comment by rzumer** [comment]
I checked the log and it seemed normal to me, but maybe the `StartSession` with `Success` = false is a cause. Abridged all requests and responses that were normal and successful.

```
201053.448|INFO| ResolveHash Request: (...)
201053.548|INFO| -- ResolveHash Response: {"Success":true,"GameID":14129}
201053.548|INFO| Successfully looked up game with ID 14129
201053.548|INFO| Loading game 14129
201053.548|INFO| FetchGameData Request: (...)
201053.955|INFO| FetchUserUnlocks Request: (...)
201053.955|INFO| Starting new session for game 14129
201053.955|INFO| StartSession Request: (...)
201053.956|INFO| POST to dorequest.php?r=codenotes2&g=14129
201054.052|INFO| -- FetchUserUnlocks Response: (...)
201054.059|INFO| Received 508 bytes from dorequest.php?r=codenotes2: (...)
201054.074|INFO| -- StartSession Response: {"Success":false}
201054.074|ERR | -- StartSession Error: Success=false
```

**Comment by Jamiras** [comment]
Mostly I was looking for the "Loading game X", no "Unloading current game", and any errors that may have occurred. The `StartSession` response is ignored, so while unexpected, it shouldn't be impacting anything.

The fact that the game ID shows up in the code notes call verifies that it's set correctly in the GameContext. Are you sure there aren't any "Unloading current game" messages after what you've provided? And if not, is the issue still reproducible?

**Comment by rzumer** [comment]
No, the very next line is `201105.917|INFO| Saving preferences...` signaling the start of the shut down process as I manually exited the application.

It should still be reproducible with the RASCV PR.

**Comment by rzumer** [comment]
Sorry, actually I think it was my mistake. The toolkit DLL version was different from the compiled interface, which resulted in this inconsistent behavior. I just recompiled the RAI DLL and the behavior reverted to normal.
