### ISSUE TITLE
Display hit count of a resetting condition while Pause on Reset triggers

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#350]
As a developer I want to know which condition with a ResetIf flag is causing the achievement to reset. This is near essential in debugging achievements with many reset conditions. The hit would be shown while the debugger is paused in the previous dll.

Currently the reset resets the hits to 0 in that condition while paused from Pause on Reset. Some form of feedback would be so helpful here. Is this a bug?

**Comment by Jamiras** [comment]
I'm not sure I follow.

> As a developer I want to know which condition with a ResetIf flag is causing the achievement to reset.

This makes sense, but the rest is kind of fuzzy. Are you refererring to 0.74 as the previous DLL? or one of the preview releases? Assuming you're commenting about a change between 0.74 and 0.75, it's mostly likely the rcheevos integration, although I'm pretty sure both versions display the dialog after clearing out the hit counts.

With the emulator paused, you can examine the memory for each condition to manually determine which one is true. From my recollection, this is how I've always determined which reset causes the pause.

See also your notes in #180:
> There is no way to see that a specific requirement is being reset without checking the address in the memory inspector.

**Comment by kdecks** [comment]
Sorry for not being clear. I'm comparing current as in 0.75 to previous as in 0.74 or before.

About my note in #180. I guess you're right. I think I must currently have had a lapse in memory.

Manually checking in an achievement with hundreds of resets, as I'm doing for one achievement is making it burdensome to know which one one is resetting. Also a reset with a > or < is much more difficult to check I've realized. There are ways around it for testing, such as adding hits and/or converting the resets into pauses temporarily.

It's not a bug. I think I'll close this issue unless you (@Jamiras) plans to turn this into action. You can reopen it if you feel it's useful as a feature request. Or you could just use #180, which I do think would be very valuable to me and most of the developers.
