### ISSUE TITLE
Bug? When "Pause on reset" is checked and there is an emulation reset, hits do not reset

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#352]
(I'm trying to get to the bottom of some unusual behavior I've seen and this is one of those things.)

I've noticed that as the title says, when "Pause on reset" is checked and there is an emulation reset, hits do not reset for that achievement. I am unsure if this is intentional.

I've tested it on 0.75 for RAsnes9x and RANES.

**Comment by Jamiras** [comment]
This is a side-effect of the logic added to prevent achievements from triggering when the emulator is reset. Normally, an achievement is disabled during the reset, then kept disabled as long as it's true. When the "Pause on reset" behavior is present, the achievement is not in the same processing queue, so it doesn't get disabled/restored in the same way.
