### ISSUE TITLE
Easier navigation through achievements in overlay

### ISSUE THREAD

**Issue by Thoooreau** [RetroAchievements/RAIntegration#355]
Currently we have to press up/down everytime to move to the next achievement in the list. When the game has too many achievements, it becomes tiring to move to a far one.

Some ideas to improve this:

- hold up/down to automatically move;
- two new hotkeys (L/R in the SNES, for example) to behave like PageUp/PageDown
  - alternative: as there will only be Achievements and Leaderboards pages now (Friends, Messages and News being cut), change Left/Right as hotkeys to move between these pages to Select, and use Left/Right to PageUp/PageDown

**Comment by kdecks** [comment]
I think this is great

**Comment by Jamiras** [comment]
Supporting additional buttons would require updating the API between the emulators and the DLL, as well and publishing new versions of each emulator.

Holding the button down seems like a reasonable solution, and something I've considered in the past - I just didn't think there was enough demand to warrant the effort required. It should also be easier to do now with some of the changes made in #354.
