### ISSUE TITLE
Is GBC banked RAM actually mappable in RetroArch?

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#364]
Posting the issue here because it's where the memory maps are defined.

From what I understand RetroArch gets a pointer to memory from the core and keeps it until reloaded.

This can only work coincidentally with GBC banked RAM. The pointer can only keep track of one bank per load. Cores default to the first bank, so it seems to work, but it doesn't actually correspond to the expected behavior.

I don't particularly like the idea of changing it to a bank 1 region and remapping the 0x10000+ region to banks 2-7, because it is messy, but unless I missed something I don't think the current map ever worked as intended outside of RAVBA.

**Comment by rzumer** [comment]
I am leaning towards pushing corrective changes for the libretro cores, and then looking at RAVBA. This will change the map again, though, so for GBC bank 1 will be at 0xD000 and banks 2-7 will occupy 0x10000 to 0x15FFF.

From what I saw with Gambatte, bank 1 contents do change with bank switching. However it might not be changing in the exact same way as how memory banks are mapped in the CPU. That means if something actually relies on bank switching working accurately in RAVBA, it will be a breaking change. I'm not aware of any set like that, and all the ones I've tested seem to work correctly in RALR/RetroArch despite the D000 to DFFF area being mapped to bank 1.

Without API changes it's not feasible to change the pointer to a memory region on RA's side at any time, so it's the only solution that I can see for all emulators to be consistent while avoiding mirroring.

**Comment by Jamiras** [comment]
RAVBA-M exposes the memory to the toolkit in a way that the toolkit reads from the address the same way the game would. The $D000 bank pointer is updated here: https://github.com/RetroAchievements/RAEmus/blob/master/RAVBA-M/src/gb/GB.cpp#L1539 and reading from it re-evaluates the bank pointer on each read.

Assuming the GBC banks are contiguous, we can probably map the $10000+ addresses back so they line up with $C000 via `cheevos_var_patch_addr`. Here's the code the dedups the mirrored NES RAM: https://github.com/libretro/RetroArch/blob/master/cheevos/var.c#L167-L174

**Comment by rzumer** [comment]
I don't think that would accomplish much. The memory map doesn't leave space to insert GBC memory banks. They have to be added at the end. The problem is that D000-DFFF is mapped to one bank (out of seven for GBC) at a time, and in libretro cores, bank switching is accomplished by changing a pointer. On RALR/RA's side memory descriptors (i.e. defining pointers to memory regions) is done once on load, so it is not possible to reproduce that functionality and always point to the current bank as far as I know. The only two reasonable options in my opinion are:
1. Keep the current map and accept that RALR/RA may always have compatibility issues when using the D000-DFFF region
2. Change D000-DFFF to map to the first bank (which makes no difference for GB, and *may* be breaking for some GBC-exclusive titles, though I am not aware of any). Then map 10000 and forward to banks 2-7 to avoid mirroring.

**Comment by Jamiras** [comment]
I wasn't proposing adding the banks in the middle. I don't know how the 8 banks are exposed via the descriptors, but if we can figure it out, we should be able to map the addresses, just like the mirrored NES addresses are being mapped.
* $C000-$DFFF -> RETRO_MEMORY_SYSTEM_RAM $0000-$1FFF
* $10000-$16FFF -> RETRO_MEMORY_SYSTEM_RAM $1000-$7FFF
In this scenario, $D000-$DFFF would be statically mapped to bank 1, which is undesirable. The static reference to bank 1 should be $10000. But it would also provide the greatest level of compatibility as you mention that most games currently using the $D000 bank function with it already statically mapped to bank 1. Games where the $D000 memory is more volatile could be modified to use the static banks.

Here's a complete list (from January) of references to $D000-$DFFF in GBC games:
[results.zip](https://github.com/RetroAchievements/RAIntegration/files/3075643/results.zip)

There's 20 unique game IDs in the list, and 88 GBC games currently, so this change would potentially affect roughly 1 in 4 GBC games.

**Comment by rzumer** [comment]
Just to be clear, 10000 corresponds to D000, not C000. And GB+GBC RAM is not allocated in one contiguous memory area in all emulators.

Are you suggesting translating 10000-10FFF to D000-DFFF, and mapping D000-DFFF to bank 1 explicitly in all emulators, or changing the map such that 10000 starts at C000 with a size of 2000 for GB and 8000 for GBC, bumping up the current 10000-16FFF region by 1000?

**Comment by Jamiras** [comment]
I'm proposing having $10000-$16FFF be banks 1-7 in all emulators, and leave $D000-$DFFF as paged memory in those emulators that support it. For those that don't support it, fix it to bank 1 - which is what I believe is currently implemented. This would provide the best compatibility with existing achievements, and changes could be made to reference the static banks when the paged bank becomes problematic.

But the more I think about it, eliminating the paged bank entirely and just fixing $D000 at bank 1 in all emulators would prevent future confusion around the issue and ensure behavioral compatibility. With $D000 fixed at bank 1, $10000 could start at bank 2 to avoid duplication. 

Most achievement writers have very little technical knowledge of these (or any) systems, and paged memory is a concept that we can't assume they would understand no matter how we describe it to them.

**Comment by rzumer** [comment]
That does make the most sense to me. If there is any game where mapping page 1 to D000-DFFF causes issues, it's not *too* difficult to replace the references, and it would be best for people to not have to worry about cross-emulator compatibility due to that detail.

**Comment by rzumer** [comment]
Closed by #366.
