### ISSUE TITLE
Access Violations

### ISSUE THREAD

**Issue by SyrianBallaS** [RetroAchievements/RAIntegration#37]
So to resolve conflicts I had to merge RetroAchievements master with my master. Tried to test a few things but exceptions keep on getting thrown. I'll add to this as I find them. I'll try to see what's wrong with them myself.  On the master branch of course.

I'll put my findings in another comment per problem I find.

## Problem 1 - Making Local Achievements
**Steps to reproduce**:
1. Load any game (I loaded Contra)
2. Click "Achievement Sets"
3. Click the "Local Achievements" radio button
4. Click "Add Achievement"
5. Double click the achievement.
6. Access violation

**Call Stack**
![image](https://user-images.githubusercontent.com/18649925/39613492-84435f92-4f35-11e8-854b-5431324ca3a6.png)

**Error**
![image](https://user-images.githubusercontent.com/18649925/39613504-9b02e892-4f35-11e8-9899-5ecdbc76cde6.png)
![image](https://user-images.githubusercontent.com/18649925/39613519-becfcee8-4f35-11e8-86f4-fe0dea2df2e8.png)

**Comment by SyrianBallaS** [comment]
Figured it out, it has to do with one of my changes. It's gonna be in #29.

**Comment by SyrianBallaS** [comment]
Problem 1.
It appears that <code>Dlg_AchievementEditor::LoadAchievement</code> tries to load conditions for the new local achievement even though no conditions exist for it.

When it calls <code>GetSelectedConditionGroup()</code>, conditions were never selected.
Then it logs <code>"ListBox_GetCurSel returning LB_ERR"</code> two times, then it throws an out_of_range exception.

**Comment by Jamiras** [comment]
Caused by my changes for #31. The Achievement constructor was previously creating an empty group that was immediately removed when loading the achievement. As a result, when creating a new achievement, there are no groups, causing the error. I have restored that functionality.

I thought I had tested that behavior. Perhaps its different in a release build. Thanks for reporting.
