### ISSUE TITLE
Limited number of conditions per group in achievement editor 

### ISSUE THREAD

**Issue by gdeOo** [RetroAchievements/RAIntegration#399]
I was trying to develop an achievement for Super Mario 64. For this achievement to work I had to check the state of a game object whose position in memory is not fixed. Luckily, however, the position is not random, it can only be one of 240 positions in an array.

Given that knowledge, I thought I could just check all 240 positions. Each individual check required 3 conditions, causing the achievement to have over 700 conditions in a single alt group. This would have been quite a pain to make in the achievement editor (and very error prone), so I generated the achievement string and put it in the XXXXX-User.txt file that contains local achievements.

The achievement worked and there was no noticeable lag, so the engine handled it fine. The issue only showed up when I tried to look at the achievement in the editor, as that caused the emulator to crash. I looked at the code and found out that the editor limits the maximum amount of conditions per group to 200. It doesn't allow the creation of more conditions when the limit is reached, so the crash is not a problem, it was caused by me editing the achievement through the file.

Having now explained my motivation for having an achievement with "a lot" of conditions, and established that it seemed to work fine, my question is: why does the achievement editor impose the 200 limit per group? Is it a purposeful limit to keep achievements small, or is it just a side-effect of how the editor's code was written (it uses a fixed std::array instead of a dynamic container)? If it is a side-effect, would it be ok to remove the limit, or raise it quite a bit?

**Comment by gdeOo** [comment]
Just FYI, if there is agreement to change anything, I'm ok with implementing it myself and opening a PR.

**Comment by Jamiras** [comment]
It's a desirable change. The array _should_ be replaced with a vector. I don't know why it was originally implemented the way it was.

If you want to try to tackle that, go for it. I don't see it as a high-priority item and it will naturally be addressed when that editor is converted to MVVM, but that probably won't happen for at least six months.

**Comment by SyrianBallaS** [comment]
Doesnt matter to me, it was originally a 3d c static array. I made it as a 2d stack based std::array.

Using vector might cause some overhead. If it doesnt I'd say vector is better. If so, raise the limit. Just know the stack cant exceed 16k collectively.

**Comment by SyrianBallaS** [comment]
Edit: I'd say make it vector if there isnt any noticeable regression on performance.

I've been extremely busy lately.
