### ISSUE TITLE
Overlay won't show after switching to fullscreen in RAVBA

### ISSUE THREAD

**Issue by SyrianBallaS** [RetroAchievements/RAIntegration#402]
I'm not totally sure where this belongs but so far I've only been able to get this issue to reproduce in RAVBA

Steps:
- Open RAVBA
- Press the overlay button (usually esc)
   - Overlay shows
- Switch to fullscreen and try again
  - Overlay doesn't show
- Even switching back to normal mode won't allow it to show either.

**Comment by Jamiras** [comment]
It's an issue in RAVBA. It destroys the window and creates a new one when toggling fullscreen, so the overlay gets destroyed as well (and not recreated). I've added an API to notify the toolkit when that occurs (#384). It'll be corrected in the next RAVBA release.

The API is not necessary in RANes, I haven't tried any of the other emulators.

**Comment by SyrianBallaS** [comment]
Yeah I tried with RAProject64 and RASnes9x and they don't have that issue.

**Comment by SyrianBallaS** [comment]
I guess a good workaround is to use something like Borderless gaming to not have to go in fullscreen mode

**Comment by Jamiras** [comment]
This was fixed with the 0.76 DLL in combination with the 1.0 release of RAVBA.
