### ISSUE TITLE
Deletion of Code Notes Should Be Dev-Only

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAIntegration#403]
Today a user was banned because they were deleting a developer's code notes out of spite. I didn't realize that this is possible to do without dev status. Considering it's doable for a standard registered account, there's nothing stopping them from creating alts to evade the ban and continue deleting notes. A lot of what we do revolves around these code notes, so I think there should be more protection in place for them.

**Comment by Jamiras** [comment]
It's possible because non-devs are allowed to edit any note so they can create their first set. Deleting a note is just setting it's text to blank. This is not an integration issue, the integration has no idea what rank a user is. This has to be enforced on the server.

**Comment by Jamiras** [comment]
Moved to RAWeb: https://github.com/RetroAchievements/RAWeb/issues/309
