### ISSUE TITLE
Linking game window showing when selecting "Edit Game Settings" in RAP64

### ISSUE THREAD

**Issue by Thoooreau** [RetroAchievements/RAIntegration#405]
(first of all, if you just cancel the window that's incorrectly showing up, everything works fine)

pre-step: if you haven't done yet, go on "File" > "Choose ROM directory..." and choose your ROMs folder. Now your ROMs should show up in RAP64 main window.

Right-click a game and select "Edit Game Settings". The "Unknown Title" linking game window shows up, even for a ROM that's already linked (it shows a different checksum).

This same window is also showing when I set up the N64DD BIOS and will start a N64DD game (like \~Bonus\~ F-Zero X) via Right-click > "Play Game with Disk". The linking game window shows up trying to link the N64DD BIOS file.

**Comment by SyrianBallaS** [comment]
I think this happened to me before as well

**Comment by eldexterr** [comment]
https://github.com/RetroAchievements/RAEmus/issues/67
