### ISSUE TITLE
Clone all Cheevos from Official/Unofficial to Local (Creating Backup)

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAIntegration#406]
A function to create a Backup (clone them all to Local) instead of clicking on each Cheevo. It would help working with the Cheevo code without constantly submitting any change to the Server for testing purpose and to have a local Backup. Alternatively but not so important a option to not delete submitted Cheevos in Local when they are being promoted to Unofficial/Core.

**Comment by Jamiras** [comment]
The 0.79 DLL allows you to multi-select achievements before hitting the clone button. If desirable, you can clone all achievements by pressing Ctrl+A when the list has focus to select them all.
