### ISSUE TITLE
Overlay input is processed while the parent window is not focused

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#410]
As reproduced with `RAppleWin`, the overlay is capturing input even when the window is not focused. This seems to be a `RAIntegration`-specific issue, because the Pause key (which toggles the overlay) will be processed only while the overlay is opened.

**Comment by Jamiras** [comment]
The overlay doesn't capture any input. It's shown when `RA_SetPaused` is called, and `RA_UpdateRenderOverlay` passes a `ControllerInput` structure that causes the overlay to be navigated and closed.

**Comment by rzumer** [comment]
I see, big oversight for RAppleWin; the keyboard emulation does not allow reliable input capture, so it only checks for keypresses independently of the window focus. Will issue a fix for that, and closing since it is an emulator issue.
