### ISSUE TITLE
AndNext conditions ignored when using AddHits

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#422]
As an achievement developer I would like to be able to add the hits of multiple AndNext groups.

I've found that if I combine groups of AndNext with AndHits, the AndNext conditions are not ignored. Still the AddHits behavior works as expected.

![image](https://user-images.githubusercontent.com/32706333/62002481-2e649b00-b0c2-11e9-8d56-0f652c8750e4.png)

Here is an distilled example of it not working as expected:

1.  0 = 1
AndNext
2. Counts A button press as hits
AddHits
3. 0 = 1
AndNext
4. 0 = 1 (5 hits)

If I press the A button 5 times this achievement will trigger.
It shouldn't because 0 != 1.
Conditions 1 and 3 are ignored.

Expected behavior would be that Condition 1 & 2 need to be true to add a hit to condition 4 OR Condition 3 & 4 need to be true to add a hit to 4.

**Comment by Jamiras** [comment]
fix included in rcheevos update
