### ISSUE TITLE
Update FormatTypes "Miliseconds" and "Frames" to show hours

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#429]
Currently time is displayed ``Minutes : Seconds . Milliseconds``. This is not easily or naturally parsed for most users. For better presentation instead display it as ``Hours : Minutes : Seconds . Milliseconds``.

I assume this is an easy update, but if it were done, I also assume all the leaderboards recorded in the old format would remain as they are, which could be the bigger problem.

**Comment by Jamiras** [comment]
This is already done in the next version of rcheevos: https://github.com/RetroAchievements/rcheevos/pull/22
