### ISSUE TITLE
Suggestion: Mastery Notification

### ISSUE THREAD

**Issue by rabbids4eva** [RetroAchievements/RAIntegration#438]
https://clips.twitch.tv/WealthyAgileLardWutFace

According to Draco665, it would be nice to see a notification for mastering a game. Like, if you earned all achievements, you'd get a popup in the middle of the emulator saying something like "Congratulations" with an icon of your profile picture, or even a special badge like a Platinum trophy on PS4 games, complete with a new sound like "Congratulations, you mastered the game!"

If you load the mastered game again, the notification of the game should say "Mastered." If you load up the emulator, the user popup should say how many sets you completed on softcore and how many sets you mastered on hardcore.

It would be nice to see this added to RAIntegration.

**Comment by kdecks** [comment]
This is great

**Comment by wilhitewarrior** [comment]
I third this. Or perhaps an image of the game icon, either way would work. It would be a pretty cool idea imo

**Comment by Jamiras** [comment]
A simple "mastery" notification has been added that will display when the user completes the last achievement in a set on hardcore. 

None of the following has been implemented:
> If you load the mastered game again, the notification of the game should say "Mastered." If you load up the emulator, the user popup should say how many sets you completed on softcore and how many sets you mastered on hardcore.

The game popup already indirectly tells you if you've mastered the game. In the second line it says how many achievements the game has, and the in the third line it says how many you've earned. If they match, then you've mastered it.

Telling a user how many sets they've mastered every time they log in is superfluous. If they really care, they can go look at their profile.

**Comment by rabbids4eva** [comment]
As for the notification sound?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
