### ISSUE TITLE
Support for Unsigned calculations in SubSource

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAIntegration#456]
Currently when you do a math like this
![image](https://user-images.githubusercontent.com/44853315/66093699-30295f80-e546-11e9-9463-c35bde6d21f3.png)

Condition 2 will be false because is a negative value, so to fix that you need to convert the value to negative using Two's complement

This was just an example but when you are trying to code more complicated achievements this is kind of a problem

**Comment by Jamiras** [comment]
There's two rather simple options you can use as workarounds for this:
1) Add an OR clause for the calculation being greater than 0x8000 (with an appropriate number of zeros based on size)
2) Adjust the total by some value so it's always positive. i.e. if you know the maximum negative value is 350, use an AddSource to add 350, thus making the total positive, and also add 350 to the comparison to correct the logic.

**Comment by eldexterr** [comment]
Why I ever do is use AndNexts to track if the value is Negative to use a different calculation (as you said), yeah maybe isn't a really big deal as you said :b
