### ISSUE TITLE
Achievement Flag: "Or Next"

### ISSUE THREAD

**Issue by wilhitewarrior** [RetroAchievements/RAIntegration#462]
And Next is a great addition but I think another good one would be an "Or Next." There have been many situations where I've really wished I had one but never one like right now.

At the moment I'm making an achievement on Resident Evil 2 for the item box to be the same way it was in the beginning. The trouble is with different unlockables and difficulty settings, there are several different items that can be in those first few slots. 
Add Hits won't work for this because I need it to be true at the time of popping and putting in a bunch of resets would be even worse than the alts. 

So as it is I have to program in about 18 alts with 64 lines of code in each one and figure out every possible combination of what could be in that box. If I had an "Or Next" I could have 2 alts and simply list each possible item in those first few slots and be done with it

Something to consider. I want to thank you again for all your hard work on this though :)

**Comment by eldexterr** [comment]
Just what I asked
https://github.com/RetroAchievements/RAIntegration/issues/432

**Comment by eldexterr** [comment]
This one can be close because the AndNext + AddHits bug was fixed 👍

**Comment by Jamiras** [comment]
AndNext allows combining multiple conditions for use in a single ResetIf/PauseIf/HitCount.

AddHits can be used to simulate all of those behaviors for OrNext:
* 0x1234 must be 1 or 2 ten times:
```
AddHits 0x1234 = 1
        0x1234 = 2 (10)
```

ResetIf can be split into multiple statements:
* reset if 0x1234 is 1 or 2:
```
ResetIf 0x1234 = 1
ResetIf 0x1234 = 2
```

And for ResetIf HitCount, use AddHits:
* reset if 0x1234 was 1 or 2 ten times:
```
AddHits 0x1234 = 1
ResetIf 0x1234 = 2 (10)
```

PauseIf can also be split into multiple statements:
* pause if 0x1234 is 1 or 2:
```
PauseIf 0x1234 = 1
PauseIf 0x1234 = 2
```

AddHits also works, creating a pause if that must be reset from an alt group:
* pause if 0x1234 is 1 or 2 ten times:
```
AddHits 0x1234 = 1
PauseIf 0x1234 = 2 (10)
```

However, using AddHits tracks the hit count over many frames. It does not require that the conditions be true in the current frame. Going back to the simple example:
```
AddHits 0x1234 = 1
        0x1234 = 2 (1)
```
This says that 0x1234 must either be 1 or 2, but only once, ever. It doesn't guarantee that it will be true for the current frame. To simulate that behavior, you have to add an AndNext/ResetIf:
```
AddHits 0x1234 = 1
        0x1234 = 2 (1)
AndNext 0x1234 != 1
ResetIf 0x1234 != 2
```
But that will reset the entire achievement, not just the AddHits clause.

The correct solution is to use Alt Groups to segregate the two parts of the Or clause. However, as Alts behave as one long series of Or's, having And'ed groups of Or's requires a combinatorial expansion of all the requirements.

As such, I believe it is still reasonable to have an OrNext flag. Anything that makes the code easier to read is generally welcomed.
