### ISSUE TITLE
Promote multiple achievements to core/unofficial at once and commit multiple achievements at once

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAIntegration#464]
I think isn't implement for a security mesure, but promoting 220+ achievements one by one isn't that funny lol
Or create a button like the one from local "Activate All" something like "Promote All" ?

Also will be pretty useful if the "Save All" button isn't only on Local, there's times when I need to save 150+ achievements one by one

**Comment by SyrianBallaS** [comment]
Souns useful but I think this would need strict access control (equivalent to a release manager). Otherwise it could be a disaster. 

I don't think role/claims-based identity is done in the toolkit and would need a dependency on raweb to make this work.
