### ISSUE TITLE
Rich presence suggestion: lookup value range feature

### ISSUE THREAD

**Issue by issac-temp** [RetroAchievements/RAIntegration#493]
While working on one game I came across a feature I was missing. 
The game in question had a bunch of different room ID's for the same dungeons or towns for example, and instead of writing:
```
Lookup:Location
350=[Oedo Town]
351=[Oedo Town]
352=[Oedo Town]
353=[Oedo Town]
354=[Oedo Town]
355=[Oedo Town]
356=[Oedo Town]
357=[Oedo Town]
358=[Oedo Town]
359=[Yamashiro / Zazen Town]
360=[Yamashiro / Zazen Town]
361=[Yamashiro / Zazen Town]
362=[Yamashiro / Zazen Town]
363=[Yamashiro / Zazen Town]
364=[Yamashiro / Zazen Town]
365=[Yamashiro / Zazen Town]
366=[Yamashiro / Zazen Town]
```
I think it would be nice to define a range of values, like this:
```
Lookup:Location
350:359=[Oedo Town]
360:366=[Yamashiro / Zazen Town]
```
It would save a lot of space in cases like this, and it could also be used together with scores for example:
```
Lookup:Score
0:1000=Noob
1001:2000=Amazing
``` 
This could be done with conditional outputs of course, but if that wouldn't be a viable option for some reason... yeah.

**Comment by Jamiras** [comment]
RAIntegration is now on a version of rcheevos containing the changes to support this. See the linked issue in the rcheevos repository for details.
