### ISSUE TITLE
Support for AND clauses in leaderboard cancel conditions

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#5]
_From @Jamiras on March 21, 2018 14:55_

I was looking at the leaderboard code and noticed the following:
https://github.com/RetroAchievements/RASuite/blame/master/RA_Integration/RA_Leaderboard.cpp#L462
The cancel condition is passed TRUE when it's evaluated, which indicates `Test` should return true if any condition is true. This effectively makes the logic be `OR` for all conditions in the Cancel field (despite still using '_' as a separator). It looks like it's been that way since it was originally added, which is further supported by the fact that it's the only `timeTest` is passed TRUE.

There are currently 171 leaderboards across 22 games that have multiple conditions in their Cancel field, most notably Super Mario Bros and Super Mario Kart.

This behavior seems idiosyncratic (and I don't believe is properly implemented in RetroArch).

I don't know if there's any easy way to fix it. Ideally we'd want to make "_" behave like an and and introduce a new symbol for or (probably "S" like achievements).

But since it's dll behavior, we can't update the existing leaderboards until a new dll is published. Maybe have an interim release that defines both "\_" and "S" as `OR`, fix all the achievements, then redefine "\_" back to `AND` in a later release?

_Copied from original issue: RetroAchievements/RASuite#58_

**Comment by meleu** [comment]
_From @kdecks on April 8, 2018 4:35_

I think this is a bug. I'll mark it as such.

**Comment by Jamiras** [comment]
Affected leaderboards have been corrected, temporary code was removed before 0.73 was released. Closing.
