### ISSUE TITLE
[Bug?] Enable Leaderboard Support in Softcore for testing purposes

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAIntegration#509]
Today I was trying to make some leaderboards for Yoshi Story and I noticed the leaderboard pop-up never appeared I though "Maybe I coded the leaderboard wrong?" (wasn't the case)
I loaded Paper Mario to see if the leaderboards appear like it should and the same thing happen, nothing, I was in softcore all this time, after all of this I activated hardcore and all the leaderboards started to function normally.

This wasn't a thing before I dunno if is a bug or was on purpose but eveytime I (and I suppose all other devs tbh) have coded and tested leaderboards I always do it in softcore, I mean everyone when is deving use softcore

**Comment by eldexterr** [comment]
Yes, I restarted the emulator multiple times, I toggle the leaderboard options and notification options but always the same :o

**Comment by Jamiras** [comment]
already fixed by #507. just delete your DLL to get the 0.77.3 non-required update.
