### ISSUE TITLE
PausePrevious and ResetPrevious Conditions

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAIntegration#512]
PausePrevious and ResetPrevious conditions would be useful to handle the previous (usually trigger or hits) piece of code more efficiently and allow to be self-containing instead of Pause or Reset the entire Achievement Code. It will add some extra fine tuning to the already existing AndNext+Execute Code by allowing to Pause (useful for time/frames) and Reset (retries) only the previous line.

The Previous Conditions would only apply to the previous line, it will not Pause or Reset the entire Achievement. Also shrink the Code due to not relying on extra workarounds.

Pause and Reset are both a non-trigger conditions which technically should be fine having it after the Trigger/Hit.

**Comment by kdecks** [comment]
#152 (Reset Group)
Also, ``PauseNext`` and ``ResetNext`` would make more sense.

**Comment by magusLOGS** [comment]
Not the entire Group, only the last line.

For example if you have a lot of lines with hits incl add hits, the Previous function would allow to handling (picking) each line with AndNext (Pause/ResetNext would not allow selective picking) but keeping everything else in the Group same, Group would reset all the hits in the current Alt.

PauseNext and ResetNext may do some sense, i was thinking the same before posting the issue but i choose Previous because i would prefer to have it on the end of the code line (after the trigger to avoid false positives), so if the Hit condition is meet (10/10), the line Previous will be ignored. Pause/ResetNext may just be a different by 1 frame (kinda like delta) as the Achievement Code works from top to bottom.

Pause/ResetNext would be -1
Pause/ResetPrevious would be +1

The more possibilities the better when working with frame accurate code, but the number of Letters for functions are limited so this would need some deeper investigation without creating to much unnecessary features.

Having PauseNext and ResetNext could be useful in some situation, its up to debate and how the technical possibilities are from Jamiras perspective.

 I see value in both Pause/ResetNext and Pause/ResetPrevious.

**Comment by Jamiras** [comment]
My first thought is immediately: Why can't these be done with an AndNext? If you want to pause a single condition, just invert the pause clause and make it a requirement for the condition. In both cases, the condition wouldn't be true while the pause condition was true.

That probably won't work for reset though, as resetting is expected to modify the HitCount on a condition. 

At a minimum, I'd prefer ResetNext over ResetPrevious as the current runtime implementation is a forwardly-linked-list (i.e. it's very difficult to traverse in reverse).

ResetNext may even be a preferable solution over ResetGroup as it gives much more control over the what should be Reset. I can't think of a single use case for ResetGroup that couldn't be handled more elegantly with a ResetNext.

**Comment by magusLOGS** [comment]
> At a minimum, I'd prefer ResetNext over ResetPrevious as the current runtime implementation is a forwardly-linked-list **(i.e. it's very difficult to traverse in reverse)**.


Thats what i thought may occur with the reverse logic behind it as the progress goes one line after another.

Stuff like looks easy on paper but is complex when dealing with RAM code. IMO Pause/ResetNext will be fine, a alternative way to what i was hoping for could be using PauseNext before ResetNext (sort of a progress blocker), interesting would also be to use ResetNext as a re-enabler for Paused-with-hit. Right now the only method is to Reset the entire Cheevo. Setting a ResetNext before PauseNext(1) with a Hit could be extremly useful. At least in theory.

**Comment by Thoooreau** [comment]
By coincidence, I'm currently working on a set in which ResetNext would help me a ton. I gotta set a hit really early in the game (which I can't check for it later, memory is tough) and then I can't reset any hits for more elaborated challenges later because of that first hit.

**Comment by Jamiras** [comment]
I'm starting to contemplate how to implement `ResetNextIf`.

It's pretty straightforward, but I want to clarify how I see it interacting with `AddHits` and `AndNext`.
```
ResetNextIf A=4
AddHits     B=18
ResetNextIf C=8
AddHits     D=11
ResetNextIf E=0
            F=10 (7)
```
In this case, it seems obvious that B, D, and F are each controlled by the preceding `ResetNextIf`, so if B, D, and F were all true and C was also true, the result would be 2/7 hits towards triggering (B+F).

However, if we remove the conditions for C and E:
```
ResetNextIf A=4
AddHits     B=18
AddHits     D=11
            F=10 (7)
```
This seems ambiguous. Based on the first example, it will only reset the hits captured by B=18, so the trigger could still fire if (D+F) tallied 7 hits. But the user may expect it to completely prevent the trigger from firing.

Similarly, if we put the `ResetNextIf` directly on F:
```
AddHits     B=18
AddHits     D=11
ResetNextIf A=4
            F=10 (7)
```
This has the same problem as the previous example. If A is true, it only prevents tallying hits from F=10. The 7 hits could still be collected from the B and D conditions.

If the intent is to completely prevent the trigger from firing, the same `ResetNextIf` should be applied to each subcondition:
```
ResetNextIf A=4
AddHits     B=18
ResetNextIf A=4
AddHits     D=11
ResetNextIf A=4
            F=10 (7)
```
This logic also carries over into `AndNext`:
```
ResetNextIf A=4
AndNext     B=18
PauseIf     C=8 (2)
```
In this case, the `ResetNextIf` will effectively make condition B false, so no additional hits will be tallied on condition C, but any previous hits tallied on condition C will not be reset. It may seem like the intent is to reset the hits on condition C, but the `ResetNextIf` has to only apply to condition B in order to support this:
```
ResetNextIf A=4
AndNext     B=18 (4)
PauseIf     C=8 (2)
```
I believe this is the correct behavior. `ResetNextIf` should only apply to the immediately following expression. (Note that `AddAddress`/`AddSource`/`SubSource` are combining logic and considered part of the following expression).

**Comment by Jamiras** [comment]
I'm going to backpedal a bit on my previous statement. `AndNext` will be treated as a combining condition, and a `ResetNextIf` will reset _all_ hit counts in the complex condition.

There is very little demand for hits within an `AndNext` chain, as the hit requirement effectively breaks the chain:
```
AndNext     B=18 (4)
PauseIf     C=8 (2)
```
C=8 will not collect any hits until B=18 has all four of its hits.



Going back to the example from the previous post:
```
ResetNextIf A=4
AndNext     B=18
PauseIf     C=8 (2)
```
The logic is to count the number of times B is 18 _and_ C is 8. So, logically, if A=4, the hit count on C=8 should be reset.

Additionally, it is likely that we would want to use an `AndNext` chain to feed the `ResetNextIf`, so `AndNext` has to be evaluated first.
```
AndNext     D=11
ResetNextIf A=4
AndNext     B=18
PauseIf     C=8 (2)
```
Here, C would only be reset if A were 4 _and_ D were 11.

If a user did have a hit target in the middle of a `AndNext` chain:
```
ResetNextIf A=4
AndNext     B=18 (4)
PauseIf     C=8 (2)
```
The `ResetNextIf` would reset all hit counts. Remember that C=8 won't have any hits until B=18 has all 4. So the situation would either be reset some number of hits on B, or reset all hits on B and some number of hits on C. In both cases, setting both B and C conditions to 0 hits does truly represent a full reset of the complex condition, so is a better pairing of the behavior to the name.

**Comment by Jamiras** [comment]
"Reset Next If" is selectable in the UI. I'm still not convinced there's any need for a "Pause Next If", whatever logic would be conditionally paused could be inverted and joined with an AndNext. i.e. "PauseNextIf a=1, ResetIf b=1 (10)" would just be "AndNext a != 1, ResetIf b=1 (10)". In both cases, the second line wouldn't tally a hit if "a = 1".

I'm going to close this as resolved.
