### ISSUE TITLE
Save Search Results and Restore previous Results

### ISSUE THREAD

**Issue by magusLOGS** [RetroAchievements/RAIntegration#518]
This would be useful when searching for a specific (hard to find) memory address/value in a large memory pool, so instead of re-doing the entire process, we could simple restore the Restults and continue the search for there.

Sometimes the Memory Viewer shows 'No Results Found', with a restore Results, we wouldn't be longer need to redo the entire process.

**Comment by Jamiras** [comment]
duplicate of #186 

Also note that you can use the "<<" button to return to the results just prior to the most recent filter. You can continue to hit "<<" to go back through the history (I think it remembers 50), or ">>" to go forward through the history once you've gone back. If you filter from any point in the history, a new history is created and you lose the ability to follow the old branch.

**Comment by magusLOGS** [comment]
Oh, i didn't knew about the "<<" and ">>". Thanks, this will do it!

I close this as it serves no purpose anymore.
