### ISSUE TITLE
Custom cheats

### ISSUE THREAD

**Issue by Alfex3** [RetroAchievements/RAIntegration#539]
I'm suggesting an option to add buttons that would change a memory address to a specific value with just one click, instead of searching that address. (Example: a cheat called "99 lives" which would make the value of the address used for lives 99). Of course, using any of those cheats would have the same effect as tampering with the RAM.

**Comment by Keltron3030** [comment]
What's the use case? It can be done in two clicks right now.  Add to bookmarks > freeze value.  Your bookmarks are saved across sessions so you can add any addresses for a game and they will be there when you reload the ROM.

**Comment by ViperZang** [comment]
It would be pretty much the same as freezing in Memory Bookmarks. You can even save/load them already too.

**Comment by Jamiras** [comment]
I agree that this is handled by bookmarks. Just bookmark the "lives" address, then either freeze it as suggested, or click on the value field and type in 99 and press enter. It's a couple extra clicks, but already completely functional.
