### ISSUE TITLE
Leaderboard OR support

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#54]
*Please disregard and close this if it's a duplicate.*

### What is Requested:
A means for leaderboard syntax to support OR logic; especially for SUBMIT, but also for START and CANCEL as they use the same syntax.

### Reason for Request:
The problem lies especially with **SUBMIT:** Most games do not have a single, stable address/value for **GAME OVER (failure)** and **GAME OVER (victory)**, but typically a developer will want to have a submit during failure or victory.

OR logic missing is the number one obstacle I've had while making leaderboards (and I've made more than most developers). Adding a method would save dozens of hours for many devs and often make impossible, possible.

### Extra Notes:
- For some games this is not an issue. Depending on the memory.
- Some games there is a (typically labor intensive) work-around: Finding an address that has one unique state for failure and another unique state for victory. Next I'd find out every other possible states of this address and excluding them. Testing it is a bitch too, because the values cant ever be used any other time in the game or you'll submit out of turn.
- Some games provide no solution at all in the memory and making separate leaderboards for victory and failure is a weak work-around.

**Comment by Jamiras** [comment]
Should be handled by https://github.com/RetroAchievements/RAIntegration/pull/31

> Achievements, Leaderboards, and Conditional Rich Presence now fully support the entire Condition lexicon, although it seems impractical to use HitCounts/ResetIf/PauseIf in Leaderboards or Conditional Rich Presence.

**Comment by kdecks** [comment]
cool cool cool; closing

**Comment by Jamiras** [comment]
Verified functionality. 

Note: A core group is still required:
```
1=1S0xH1234=6S0xH1234=9
```
but can be left empty:
```
S0xH1234=6S0xH1234=9
```
this _does not_ work:
```
0xH1234=6S0xH1234=9
```

**Comment by Jamiras** [comment]
Note that these changes are present in the 0.73 version of RA_Integration, but the empty core group is not supported by current versions of RetroArch.
