### ISSUE TITLE
"Revert Selected" breaks achievements

### ISSUE THREAD

**Issue by jared6502** [RetroAchievements/RAIntegration#583]
After making changes to an achievement, using the "Revert Selected" button breaks the achievement, causing it to be untouchable without restarting the emulator. Sometimes is accompanied by a crash.

process:
-Make a change to an existing local achievement
-Click the Revert Selected button
-Get a popup asking "Attempt to revert this achievement from file?", click yes
-Get error popup saying "Couldn't find this achievement!"
-Achievement is not reverted to previous state, and revert button does nothing
-Achievement can no longer be edited after switching away from it

Tested with both RALibRetro and RANes

RA_Integration.dll version is 0.78.1.0

**Comment by Jamiras** [comment]
I've verified this behavior at least as far back as 0.76.0. When the "Couldn't find this achievement!" message is shown, the achievement is destroyed assuming it was removed from the file. However, the entry is not removed from the list, which creates the weird limbo you describe.

I've change the behavior to not destroy the achievement, allowing the user to either save the current state of the achievement, or explicitly delete the achievement themselves.

Additionally, I've fixed the code so the achievement should be found unless it actually has been removed from the file.
