### ISSUE TITLE
Bug Report - Code Note pop-up's search field not active if clicked on after using another program.

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RAIntegration#585]
If you type somewhere else, click on the code note search field, and start typing... whatever you type will end up in the prior source, whether it be Chrome, DIscord, etc.

It's really odd and confusing to explain. Here's an example:

I just clicked on the code note search and started typing this sentence.

![Capture](https://user-images.githubusercontent.com/45054151/86193997-f5734880-bb12-11ea-8064-f21997ae48f9.PNG)

Clicking on the code note window won't do anything either. You have to click on any other RALib window first and *then* click on the code note window.

**Comment by Ben-Ghazi** [comment]
Just had this happen to me and it's kind of annoying. Judging by my alt + tab window order the problem is clicking on the code notes window doesn't change the active window like it should so it just sends your text to whatever is the active window at the time.

**Comment by televandalist** [comment]
Thank you 😌
