### ISSUE TITLE
Bug Report - Local achievements not loading when the site is down.

### ISSUE THREAD

**Issue by Ben-Ghazi** [RetroAchievements/RAIntegration#591]
Core and unofficial achievements are (understandably) not loaded but local achievements also aren't loaded despite being read from a file.

Interestingly enough, the emulator still recognized my login was valid.
![Capture](https://user-images.githubusercontent.com/39404689/90301514-07603f00-de66-11ea-98e7-756e8265a1bb.PNG)

**Comment by Jamiras** [comment]
The "Cannot load achievements" error actually occurs when you try to resolve the hash without being logged in. The hash is still required to locate the local achievements as the local file name includes the game id, so local achievements _cannot_ currently be loaded without being able to communicate with the site.

As for the login "working", you can reproduce this error even when the site is not down. If you open a recent game before the login completes, you'll see the same error, then your login dialog will appear just as you've captured. 

Another way to see that dialog is to logout and then try loading a game.

I don't believe this to be a bug. You're describing functionality that would be handled by the offline mode feature: #21
