### ISSUE TITLE
Indirect memory addresses: pointers, etc

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAIntegration#60]
As a developer, I want to be able able to reference memory that may not always be at the same address.

To simplify the explanation, I use the following conventions:
* `$` is a memory reference
  * `$1234` means the memory at address `0x1234`. 
* `0x` is a constant
* both are hex encoded
* `()` indicates order of operations: 
  * `$(0x5678 + $1234)` means: take the memory at address `0x1234`, add `0x5678`, and get the memory at the resulting address.

There are four scenarios to consider:
* **Direct pointer**: A direct pointer is a memory address that points at another memory address of interest.
  * `$($1234)`
  * `$1234` contains `0x5678`, condition should look at `$5678`.
* **Indirect pointer**: An indirect pointer is a memory address that points at a chunk of memory where the memory of interest is always N bytes from the pointed-to memory. N is typically the offset of a field within a structure, but it could also be a constant index into an array.
  * `$($1234 + 12)`
  * `$1234` contains `0x5678`, condition should look at `$(0x5678 + 12)`, i.e.`$5684`
* **Array index**: The memory address specifies the number of bytes to offset a known address by.
  * `$(0x5678 + $1234)`, alternately notated as `$(0x5678[$1234])`
  * `$1234` contains `6`, condition should look at `$(0x5678 + 6)`, i.e. `$567E`
* **Scaled array index**: The memory address specifies a number of units to offset a known address by. A unit is some number of bytes that may represent a simple data type (2 for 16-bit values, 4 for 32-bit values) or a complex data type (i.e. 48 for a character sheet in an RPG)
  * `$(0x5678 + $1234 * 16)`, alternately notated as `$(0x5678[$1234*16])`
  * `$1234` contains `6`, condition should look at `$(0x5678 + 6 * 16)`, i.e. `$56D8`

In all of these scenarios, a known memory location (`$1234`) can be used to determine a dynamic address that the condition depends on. All of the scenarios also fit into the formula: "read memory at address, multiply by scalar, add constant, and read memory at result":

* **Direct pointer**: `$($1234 * 1 + 0x0000)`
* **Indirect pointer**: `$($1234 * 1 + 0x000C)`
* **Array index**: `$($1234 * 1 + 0x5678)`
* **Scaled array index**: `$($1234 * 16 + 0x5678)`

As such, the proposal below attempts to fit that formula into the existing framework with the smallest amount of overhead.

A new flag `AddAddress` will be used to indicate the result of the current row will be added to the address field of the next row. The comparison column will be changed to a multiplication symbol (fixed).

**Direct pointer**: Condition `$($1234)` is `3`
```
AddAddress Mem 16-bit 0x1234 * Value 1
           Mem 8-bit 0x0000 = 3
```

**Indirect pointer**: Condition: `$($1234 + 12)` is `3`
```
AddAddress Mem 16-bit 0x1234 * Value 1
           Mem 8-bit 0x000C = 3
```

**Array index**: Condition `$(0x5678 + $1234)` is `3`
```
AddAddress Mem 8-bit 0x1234 * Value 1
           Mem 8-bit 0x5678 = 3
```

**Scaled array index**: Condition `$(0x5678 + $1234 * 16)` is `0`
```
AddAddress Mem 8-bit 0x1234 * Value 16
           Mem 32-bit 0x5678 = 0
```

Because the `AddAddress` line looks like a condition line (except for the '*'), it won't require a fancy new UI, and should be fairly easy for developers to use (assuming they understand how pointers work in the first place). You can also see illustrated above how easy it would be to specify the size of the pointer (or index) using the existing "16-bit/8-bit" dropdown. The direct pointer example uses a 16-bit pointer. The two array index examples use an 8-bit index. The scaled array index example shows the other side of the coin where a 32-bit value is pulled from the calculated memory address.

This structure also leaves the flag field blank on the condition line, allowing for the use of `ResetIf` or `PauseIf` constructs dependent on the indirect memory. The `Hits` column would be ignored for the `AddAddress` lines, but still usable normally on the final condition line.

You can also combine multiple `AddAddress` lines to something more complex. Here's a scaled array pointed at by a direct pointer:
```
AddAddress Mem 16-bit 0x1234 * Value 1
AddAddress Mem 8-bit 0x5678 * Value 16
           Mem 16-bit 0x0004 = 3
```
Which is `$($1234 + $0x5678 * 16 + 4) == 3`.
The first line is the pointer to the data structure array.
The second line gets the Nth item of the array, where each item is 16 bytes long.
The third line gets the 16-bit value 4 bytes into the structure.

**Comment by Jamiras** [comment]
Open question: if the condition line contains addresses on both sides of the comparison, does `AddAddress` apply to both, or just the one on the left? 

The primary use case for an address on the right is for delta comparisons (`$1234 < delta $1234`), in which case, the `AddAddress` would be expected on both sides.

Perhaps the best solution would be to only apply it to the right side if the address is the same as the left side?

**Comment by Jamiras** [comment]
Probable snag for direct pointers: the integration DLL doesn't map addresses directly. A pointer to $7F1011 might map to $001011 or $0109011 or something similar in the integration DLL because any non-relevant addresses are collapsed when building the mapping.

**Comment by salvadorc17** [comment]
How far is this for completion and what else can be done with AddAddress for addresses that adds offset value to base address, that does not requiere pointers.

**Comment by Jamiras** [comment]
Adding an offset to a base address is the "Array index" example above.

Besides the plan outlined above, no work has actually started on this feature. It is something I would like to get into 0.77, but I'd really like to get the UI in a better state first so it'll be easier to implement the "* value" portion of the logic.
