### ISSUE TITLE
RAGoals

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#64]
@Jamiras, @SyrianBallaS, @GameDragon2k, @leiradel, @ScottFromDerby, @luchaos

Hey guys, I've been talking with @ScottFromDerby and @leiradel about the bright and promising moment we, at RetroAchievements scene, are experiencing. We have a bunch of very skilled guys contributing with the project and this is freaking awesome.

However, we are a bit scattered. Each one of us is making great contributions but each with their own focus. I have a strong conviction that if we make a roadmap and share the same goals, we will achieve better and faster results and also avoid wasting of time on unnecessary work.

That being said, let me list here some goals we are aiming for RAIntegration in a hope that we can direct the efforts to them.

## decouple the achievement triggering/testing code from RAIntegration 

The main reason for it is that currently it's a pain to maintain two codebases for the same thing (here and on RetroArch).

RetroArch users are a big slice of our user base (I dare to say they are more than 50%), and any new feature implemented in RAIntegration must consider compatibility with RetroArch.

The good news is that @leiradel is already working on this front.

**UPDATE:** here's the repo where this is being worked: https://github.com/RetroAchievements/rcheevos

## ability to develop achievements with Lua

This will be really cool. Achievement developers will be freed from many of the existing limitations of the current toolkit.

Good news here too: @Jamiras and @leiradel are working on this front.

We still need to make some adjustments on the server side to make it a real thing, but I already started to discuss it with @luchaos. I hope we can solve it soon.

## add RAIntegration support on the Windows version of RetroArch

Currently we have RALibretro, but as you may know it lacks some basic features (e.g.: input remapping) and implementing them from scratch is like reinventing the wheel.

The good news here is that @leiradel told me that the leadership of RetroArch is in a good agreement about adding RAIntegration support on the Windows version of RetroArch.

The new RetroArch WIMP GUI should be a good interface to use while developing achievements. It's powered by Qt, and it's exactly the subject of the next topic.

## port RAIntegration from Win32 API to Qt

This is a long-term goal. I recognize that this requires a good amount of effort, but I want to highlight this as a goal in a hope to prevent the current development from moving toward a more intensive use of Windows-only solutions.

We know that some libretro guys are interested on this Qt port, and maybe they can help here at some point.

Being able to develop achievements on Linux is like a dream for me and I'm sure that it would also bring many knowledgeable people to the scene (*cough* @RobLoach *cough*).

IMHO making the cheevo development toolkit be cross-platform is a huge contribution to its longevity.

**Comment by RobLoach** [comment]
I know the task of porting from Win32 to Qt is a big one. While I don't have much experience with RetroAchivements, I'm more than willing to help test the compilation process and such on Linux.

**Comment by SyrianBallaS** [comment]
Yeah, with the code as it is, it will be extremely difficult to translate it to Qt. Most modern APIs follow Object-Oriented, RA_Integration seems to follow the old "C with Classes" (Data-Oriented; C++98) paradigm. Such as no globals, Single-Responsibility Principle, dependency injection, and more focus on interfaces than singletons (oh how they make me cringe, RA_Integration is full of them; singletons). 

I have used Qt in the past before before ASP.NET Core was a thing and they fundamentally work the same. I was trying to fix up the code a little bit before doing more ambitious stuff. 

If we do port it over to Qt or even ASP.NET Core as web service dll, it should be simple to integrate with the existing emulators via IPC (Inter-Process Communication). Seems a ways off though. I do appreciate your (@meleu) ideas regardless as they seem pretty good. Wouldn't really know the first thing for the other two.

**Comment by leiradel** [comment]
Let's not go fancy on this if we want to add it to RetroArch. RetroArch is a C89 application, and only allows anything different from that on very specific cases. Qt is mentioned here because RetroArch already embeds Qt as **one of** it's UIs.

The first step on this front is to integrate `RA_Integration` into RetroArch (only for the Win32 x86 build of course), then we will have RetroArch people looking at it and then we can start designing something that will work for both parties.

**Comment by Jamiras** [comment]
How would integrating RA_Integration into RetroArch look? I don't think converting the entire codebase to C89 is feasible, or desirable. Refactoring the code such that we could use a QT UI and build a linux .so is desirable, and possible, but there's a lot of upfront work that would have to happen first.

I'm not familiar with QT, but I've already been thinking about moving the code more towards an MVVM model for unit testing. Right now everything's all tangled together - UI/logic/data/server interaction. MVVM allows for the UI state to be managed by a data structure that can be unit tested, then any UI can be put on top of it and just be notified of changes in state to update the UI, and UI interactions would update state. I prefer MVVM over MVC as the UI can consume the state however it wants, making it easier to change the UI in the future.

Regarding dependency injection/singleton usages. I agree that the current model is not ideal. Personally, I prefer the service locator pattern, where singleton-type dependencies (services) are all stored in one location and can be retrieved as needed instead of every class having references to all of their dependencies all of the time.

**Comment by leiradel** [comment]
> How would integrating RA_Integration into RetroArch look? I don't think converting the entire codebase to C89 is feasible, or desirable.

It would be by using the integration DLL directly, Win32 API and everything. There would be a special RetroArch build for Win32 targeted at achievements developers.

**Comment by luchaos** [comment]
Minor note, I hope this doesn't disrupt this conversation too much: 
All of this sounds incredibly similar to the changes I'm currently working on for RAWeb by refactoring the flat/procedural PHP code, that has a lot of globals and tightly coupled code as well, to the Laravel framework (MVC, DI, AR, testable code). Having that shift in paradigm on both the server and client side sounds awesome  :)

**Comment by SyrianBallaS** [comment]
@leiradel 
While I know how to program in ANSI C, it is not desirable and seems counter-productive. What we could do is rewrite the dll exports a little bit to be used as C callback functions, meaning no C++ code in the callbacks but the original exports would need to converted to member functions to minimize changes. RetroArch then can import those functions (which for some reason dll importing isn't there yet) to use as they would be ANSI C compliant.

@Jamiras 
MVVM seems like a good approach for a C++ app. I'm more used to MVC,DI myself but DI should be able to work to MVVM. Not totally sure if Qt has a support for json files/database tables as classes like ASP.NET does but w/e, MVVM still seems good for us.

**Comment by leiradel** [comment]
> While I know how to program in ANSI C, it is not desirable and seems counter-productive.

Depends on experience and goals ;)

> What we could do is rewrite the dll exports a little bit to be used as C callback functions

It would be great to have a C API. RA_Integration would be able to do anything it wanted internally while keeping external usage simple.

Just keep in mind that, if we want to use RA_Integration in RetroArch, building it must be simple (RetroArch uses a Makefile), and external dependencies must be kept to a minimal.

**Comment by meleu** [comment]
Let's try to leave aside our technical preferences for a moment and look to the goal that undoubtedly is shared by all of us: **RetroAchievements longevity**.

Integrate RAIntegration with RetroArch is the way to achieve that. Two points to enforce why I'm saying that:

1. A quick glance at our RA stand-alone emus is enough to show how outdated they are. Now if we look at RetroArch's commit history we'll see how highly active its development is.

2. RetroArch is cross-platform. A good portion of our user-base use Android or those gaming systems for Raspberry pi to earn achievements (other platforms with cheevos feature: Linux, Mac, PS Vita, PS 3, Wii U). It's only possible because of RetroArch supports it.

The ability to be compiled to such a varied range of platforms is a really impressive thing. And the fact that RetroArch is picky about following C89 is one of the reasons this is possible.

@Jamiras said:
> I don't think converting the entire codebase to C89 is feasible, or desirable

We don't want to convert *everything*, but only the parts that must be executed on the "player's side" (because of the point 2 I've said above). Basically the parts responsible to build the achievement's list and then test if their conditions are met.

The cheevo development toolkit doesn't need to run on such a wide range of platforms (by the way, the RetroArch's WIMP GUI we talked about runs only on Windows and Linux). The toolkit can be developed with C++, no need to adhere C89. However it's still important to avoid to add many external dependencies besides Qt.

**Comment by meleu** [comment]
Just a heads up about two topics I mention in the OP...

## decouple the achievement triggering/testing code from RAIntegration

This is being worked by @leiradel here: https://github.com/RetroAchievements/rcheevos

If I'm not mistaken @Jamiras already used the `rcheevos` approach in a "custom" RA_Integration.dll build to develop and test a complete achievement set. Then I believe it will be officially released soon.

The next step is to use `rcheevos` in RetroArch too.

## ability to develop achievements with Lua

@Jamiras worked on it via `lua_cond` branch: https://github.com/RetroAchievements/RAIntegration/tree/lua_cond

We still need to make some work on the server-side, but it'll be done after migration to the new and refactored back-end's codebase. Probably next month.

**Comment by Jamiras** [comment]
Two corrections:
1) the lua_cond branch is dead. lua runtime support will be handled by rcheevos, and I will reimplement the UI portions after PR 76 is merged.
2) I did not expect to "release soon" the code using rcheevos. I want to release what we have as-is when RetroArch 1.7.4 is released before starting to merge in some of the larger refactorings (including the rcheevos one). This would coincide with a RetroArch release that consumes rcheevos. That release would also add UI to support the new features of rcheevos, including lua and 24-bit values.

**Comment by meleu** [comment]
@Jamiras Thanks. I've updated my previous post and I hope to be more accurate this time.

**Comment by Jamiras** [comment]
I've created discussions #761, #763, and #765 to track the remaining items here.
