### ISSUE TITLE
Request: OSMC integration

### ISSUE THREAD

**Issue by iosoft** [RetroAchievements/RAIntegration#677]
Friends,

I am using OSMC on my Raspberry Pi.
I also installed and play some NES and SNES games in it.

Pls integrate RetroAchievements with OSMC.

It will be awesome.

**Comment by Sanaki** [comment]
As with the other issue I closed, this is out of scope for this repo. That said, this is also a bit outside the realm of what we would do. If they wanted to implement rcheevos support themselves, that's something they could do. That would be from the rcheevos repo, not this one. We only directly implement support in RetroArch (which is already fully supported) and in specific dev-oriented emulators, which is what this repo enables.
