### ISSUE TITLE
RA_Log has double newlines

### ISSUE THREAD

**Issue by ScottFromDerby** [RetroAchievements/RAIntegration#71]
![image](https://user-images.githubusercontent.com/36479414/42573268-8487eeb4-8513-11e8-9aac-87799605a763.png)

**Comment by Jamiras** [comment]
Note that calling `RADebugLogNoFormat` does not append newlines, so you also have situations like this:
```
{"Success":true,"User":"Jamiras","Token":"fDvmDBC3bILyXNKr","Score":69631,"Messages":0}RAWeb::CreateThreadedHTTPRequest added 'RequestFriendList'
```
The RAWeb::CreateThreadedHttpRequest starts a separate message.

**Comment by Jamiras** [comment]
We should also consider adding timestamps and support a rolling log - currently, the file will just keep growing forever. I'd also recommend moving it up one level, so it's directly in the `RACache` directory, instead of buried in the `RACache\Data` directory.
