### ISSUE TITLE
Rework "News" overlay

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAIntegration#75]
The existing News overlay renders the raw HTML that appears in the News section of the home page. 

![image](https://user-images.githubusercontent.com/32680403/43025084-977c4eb8-8c2d-11e8-9189-e3077539b64b.png)

There's enough information in the JSON received from the server to do a decent job of mimicing the server behavior. 

In addition to "fixing" the display behavior, the News overlay should be featured in the emulator until the user selects a game.

Alternately, we should stop fetching the News data on startup as most users probably never use it.

**Comment by rzumer** [comment]
News were removed, so I think this can be closed.
