### ISSUE TITLE
Ability to sort Achievements list

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#8]
_From @Jamiras on March 21, 2018 15:6_

As a developer, I'd like to be able to sort the achievements list by ID, title, points, or possibly even author.

_Copied from original issue: RetroAchievements/RASuite#61_

**Comment by Jamiras** [comment]
The achievement list can now be sorted by clicking on the headers. This does not modify the order on the server. That functionality is described in #130.
