### ISSUE TITLE
Achievement cannot be created with MemAddr larger than 2K

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RAIntegration#82]
As a developer, I want to create an achievement with many conditions. The UI doesn't limit me, but things start going back when the serialized string exceeds ~1900 bytes.

There's two major issues contributing to this.
1) `AchievementSet::SaveToFile` uses a 2K buffer to write each line of the XXX-User.txt file. With the additional space taken by the achievement title, description, and other attributes that leaves around 1900 bytes for the MemAddr string.
2) `AchievementSet::LoadFromFile` uses a 4K buffer read each line of the XXX-User.txt file, so even if you used another tool (RATools/Notepad) to generate a more complete achievement, it still couldn't be loaded.

These methods should be modified to support larger achievements now that the database does.

**Comment by meleu** [comment]
@Jamiras is this still an issue on 0.73?

**Comment by Jamiras** [comment]
Yes, I didn't get around to fixing it in the current implementation, and have some ideas that will simplify the solution after some other planned changes.
