### ISSUE TITLE
[feature request] Hardcore Mode as default

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#86]
I guess there's no need to repeat here what already discussed in discord, right?

Many active members and the leadership agree that the hardcore mode should be enabled by default on the first run of the RAEmus. If users want save/load state, they need to disable hardcore mode.

Just to put very clear, this request is only about making hardcore mode be the default mode on the first run. Nothing more, nothing less.

EDIT:
@Jamiras mentioned on Discord something about showing a message when the user tries to save/load a state while in hardcore mode. Alright, that would be cool too! :+1:

**Comment by Jamiras** [comment]
It's always best to document intent as best as possible. Discord is notoriously hard to search through and if this sits around for a while, that information will be lost.

My summary of the discussion is that everyone agrees hardcore should be the default, but we cannot eliminate softcore - and should actually improve the softcore experience if possible (store achievement state along with save states, but not as part of this issue).

My comment in regards to the message is that a dialog _already appears_ when the user attempts to load/save a save state (at least in RANes and RASnes9x - will verify other emulators).

![image](https://user-images.githubusercontent.com/32680403/44238242-10cc4900-a171-11e8-895a-e6788914f45b.png)

This message is in the emulator itself, but as we'll already be publishing new emulators for #14, now might be a good time to move it into the DLL and improve the wording. Thoughts?

**Comment by Jamiras** [comment]
It looks like the default was changed over a year ago: https://github.com/RetroAchievements/RAIntegration/commit/6b5559987e21d2a6cf029261e6ed654f1bcfd6fb

So, unless we want to do something with the dialog, there's no work to do here.

**Comment by Blazekickn** [comment]
ah, ok. Haven't needed to re-dl rap64 so i didn't notice. just remember getting frustrated about that at some point

**Comment by Jamiras** [comment]
The dialog usage will be standardized in the emulators via https://github.com/RetroAchievements/RAEmus/pull/11. Closing this ticket.
