### ISSUE TITLE
Non-ASCII characters are not sent correctly in code notes

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#88]
This is a regression, as this was working as of January. Characters outside of standard extended ASCII, such as `ō`, are either replaced by standard ASCII "equivalents" (in this case by `o`), or by interrogation marks (at least for Chinese characters, e.g. `好`).

The database was updated recently to support UTF-8 characters in code notes. They are currently not displayed correctly on the website, but this will be fixed in a future update (likely 2.0.0). In the meantime, support should be restored on the side of RAIntegration as well.

A secondary issue is that characters outside of standard ASCII, i.e. extended characters such as `ö`, now return an error despite being sent and processed correctly by the server. This can be moved to a separate issue once confirmed if the solution is different from that of the main issue.

**Comment by Jamiras** [comment]
It is most likely this change from `wchar_t` to `TCHAR` that caused the change in behavior: https://github.com/RetroAchievements/RAIntegration/commit/5dc0a4429305e6733d04f4514fa19eb123e972f0#diff-f7fce8e53847706f450b664372f2e40eL1045, which went into the 0.069 release in February.

Changing this to explicitly use GetDlgItemTextW correctly reads the string and converts it to UTF-8, which does display correctly from the website. Therefore, something else happened that invalidated any pre-commited data you are referencing.

The last time I tried to fix a Unicode display issue, it was shot down (see #83).
