### ISSUE TITLE
Code Note Menu crashes when loading List with deleted Notes

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAIntegration#957]
Resetting the Code Note filter in the Code Note Menu can crash the emulator under specific circumstances. It seems to be related to the emulator trying to load a note that does not exist anymore.

**Steps to Reproduce:**
1. Load any game and open the Memory Inspector and Code Note Menu
2. Create a temporary note on an undocumented address without publishing
3. Do a search with a filter String
(doesn't matter if the newly noted address is part of the results or not)
5. Remove the code note again
6. Press "Reset" in the filter

If done correctly it should crash the emulator, without an error message.
I tried the same method but with publishing the note in Step 2 and then when crashing it throws this error message:
![image](https://user-images.githubusercontent.com/45672834/213185805-4327ec40-5fd0-4ca7-bd75-f5374860db8c.png)

**Comment by Jamiras** [comment]
Found earlier and fixed via https://github.com/RetroAchievements/RAIntegration/commit/15d22361540b39ef343f51bdee1c8c923c5847d4

This does result in an empty note being displayed in the list. I'll make further changes to address that.
