### ISSUE TITLE
Achievement's icon in progress indicator widget is monochrome

### ISSUE THREAD

**Issue by kmpers** [RetroAchievements/RAIntegration#988]
Local badges are displayed in colour:
![local](https://user-images.githubusercontent.com/102823900/226963666-6997e42d-f32e-469a-867d-321289b07f32.png)

Uploaded badges are grayscale:
![335212](https://user-images.githubusercontent.com/102823900/226964576-52c714b9-6ac3-4a05-831e-3945f82bbfc2.png)

**Comment by Jamiras** [comment]
This is intended. Until the badge is unlocked, it should be greyscale, but the greyscale version of the badge doesn't exist until it's uploaded to the server.
