### ISSUE TITLE
Line-Breaks in Code Notes wrongly translated in Emulator

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RAIntegration#995]
With the new feature to edit code notes on site, there seems to be a small issue with the code note field translating simple line breaks (Enter) wrong when the last edit was made from the site.

Since I have no actual explanation why it's happening, I include some screenshots explaining the problem.

Code note on address 0x3D906A made in the emulator:
![image](https://user-images.githubusercontent.com/45672834/233113649-f3755319-9420-4999-9816-efebea8aebc2.png)

Full note on the website's code note page:
![image](https://user-images.githubusercontent.com/45672834/233110031-8b256959-6250-4e7e-982a-3efad88ccbca.png)

Editing the code note via website (here I changed Bit2 to Bit0) and press save. Website still looks fine:
![image](https://user-images.githubusercontent.com/45672834/233110687-22d90cf2-9ff6-4d53-94f5-facdcaa61329.png)

Loading the game in the emulator and checking the code note for address 0x3D906A:
![image](https://user-images.githubusercontent.com/45672834/233113177-fc9da872-ce44-46b9-a1b2-da5622f23d69.png)

Important to mention is that the line breaks still exist in the code note, just isn't working in the code note editor editor field. You can still see the line breaks in the code note filter, doing an edit and saving again still shows the line break on the website and if you edit the code note you can "remove" invisible characters where the line breaks originally were.

**Comment by Jamiras** [comment]
Fixed by #996
