### ISSUE TITLE
Wiped local code notes not processed upon re-opening.

### ISSUE THREAD

**Issue by redwizard42** [RetroAchievements/RAIntegration#997]
If I go to 'erase' a code note by clearing its contents, but do not publish the erasure, an entry is made in the user text for the blank local code note.  If I re-open the emulator/re-load the game, these blank local notes are ignored.

Example:

I created two notes "dummy note" in Game 355. One at Address 0x21ffd and one at 0x21fff, which results in this in the User-355.txt:
1.2.0.0
Legend of Zelda, The: A Link to the Past
N0:0x021ffd:""
N0:0x021fff:""

If I reload the game or if I reload RALibretro and either go to the address in memory inspector or code notes window, those notes show up as "dummy note" rather than a blank local note.

**Comment by Jamiras** [comment]
I can only reproduce this if the editor windows are open before loading the game.
